// Fight Cute — controls.js
function drawMatch(){if(!match)return;const g=arenaCtx,t=match.elapsed,camera=(match.player.x+match.npc.x)/2-320;g.clearRect(0,0,640,360);g.save();if(match.shake&&!motion.matches)g.translate((Math.random()-.5)*match.shake,(Math.random()-.5)*match.shake);drawEnvironment(g,t,camera);drawFighter(g,match.player,t);drawFighter(g,match.npc,t);for(const q of match.particles){g.globalAlpha=clamp(q.life/.4,0,1);g.fillStyle=q.color;g.fillRect(q.x,q.y,q.size,q.size);}g.globalAlpha=1;for(const q of match.numbers){g.globalAlpha=Math.min(1,q.life*2);g.fillStyle=q.color;g.font='bold 10px monospace';g.textAlign='center';g.fillText(q.text,q.x,q.y);}g.globalAlpha=1;g.restore();}
function showBattleOverlay(title,text,finished){resetArenaInput();document.querySelector('#battle-result-title').textContent=title;document.querySelector('#battle-result-text').textContent=text;document.querySelector('#battle-resume').hidden=finished;battleOverlay.hidden=false;(finished?document.querySelector('#battle-rematch'):document.querySelector('#battle-resume')).focus();}
function endBattle(title){if(match.ended)return;match.ended=true;match.announce='';match.announceUntil=0;showBattleOverlay(title,title==='PLAYER WINS!'?'Nice fighting! Your cute champion wins this round.':title==='DRAW!'?'A perfectly matched pair. Try another round!':'The NPC wins this time. Ready for a rematch?',true);updateBattleHUD();}
function pauseBattle(){if(!match||match.ended||match.paused)return;match.paused=true;showBattleOverlay('PAUSED','Take a breather. Your arena will be right here.',false);}
function leaveBattle(){matchLoad++;battle.hidden=true;battleOverlay.hidden=true;resetArenaInput();match=null;openMaps();}
document.querySelector('#match-pause').addEventListener('click',pauseBattle);document.querySelector('#battle-resume').addEventListener('click',()=>{battleOverlay.hidden=true;match.paused=false;document.querySelector('#match-pause').focus();});document.querySelector('#battle-rematch').addEventListener('click',()=>beginMatch(match.map));document.querySelector('#battle-maps').addEventListener('click',leaveBattle);
for(const [id,type]of [['attack-btn','attack'],['heavy-btn','heavy'],['skill-btn','skill'],['ultimate-btn','ultimate']])document.querySelector('#'+id).addEventListener('click',()=>doMove(match.player,type));document.querySelector('#jump-btn').addEventListener('click',()=>battleJump(match.player));
const guardButton=document.querySelector('#guard-btn');guardButton.addEventListener('pointerdown',e=>{if(scene!=='battle')return;guardButton.setPointerCapture(e.pointerId);guardTouch=true;guardButton.classList.add('held');});for(const type of ['pointerup','pointercancel','lostpointercapture'])guardButton.addEventListener(type,()=>{guardTouch=false;guardButton.classList.remove('held');});
const joystick=document.querySelector('#joystick');function moveStick(e){if(stickPointer!==e.pointerId)return;const r=joystick.getBoundingClientRect(),nx=(e.clientX-r.left-r.width/2)/(r.width*.34),ny=(e.clientY-r.top-r.height/2)/(r.height*.34),len=Math.max(1,Math.hypot(nx,ny));joystickX=Math.abs(nx)<.17?0:clamp(nx,-1,1);document.querySelector('#joystick-thumb').style.transform='translate('+(nx/len*42)+'px,'+(ny/len*42)+'px)';if(ny<-.7)battleJump(match.player);}
joystick.addEventListener('pointerdown',e=>{if(scene!=='battle'||match.paused||match.ended)return;stickPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);moveStick(e);});joystick.addEventListener('pointermove',moveStick);for(const type of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(type,()=>{joystickX=0;stickPointer=null;document.querySelector('#joystick-thumb').style.transform='translate(0,0)';});
addEventListener('keydown',e=>{if(scene!=='battle')return;const k=e.key.toLowerCase();if(k==='escape'){e.preventDefault();if(match.paused&&!match.ended)document.querySelector('#battle-resume').click();else pauseBattle();return;}if(!battleOverlay.hidden){if(k==='tab'){const buttons=[...battleOverlay.querySelectorAll('button')].filter(b=>!b.hidden);const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(['a','d','w','r','j','k','e','q',' ','arrowleft','arrowright','arrowup'].includes(k)){e.preventDefault();arenaKeys.add(k);if(!e.repeat&&['w',' ','arrowup'].includes(k))battleJump(match.player);}});
addEventListener('keyup',e=>arenaKeys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{resetArenaInput();if(scene==='battle')pauseBattle();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&scene==='battle')pauseBattle();});
function battleFrame(now){const dt=Math.min(.033,(now-lastBattleFrame)/1000||.016);lastBattleFrame=now;if(scene==='battle'&&match){updateMatch(dt);drawMatch();match.lastHUD+=dt;if(match.lastHUD>.05){match.lastHUD=0;updateBattleHUD();}}requestAnimationFrame(battleFrame);}requestAnimationFrame(battleFrame);
