/* Three replayable, in-world puzzle encounters per expedition. */
const expeditionPuzzleTypes={cloud:{name:'Cloud Stepping-Stone Sequence',category:'B · PLATFORMING'},wind:{name:'Windmill Redirect',category:'A · ENVIRONMENT'},guardian:{name:'Sleeping Guardian Bypass',category:'D · COMBAT / C · EXPLORATION'}};
function makeFreePuzzles(w,rng=Math.random){const order=['cloud','wind','guardian'];for(let i=2;i>0;i--){const j=Math.floor(rng()*(i+1));[order[i],order[j]]=[order[j],order[i]];}const grounds=w.platforms.filter(p=>p.ground),level=w.index+1;w.puzzles=order.map((type,i)=>{const ground=grounds[1+i*2],x=ground.x+45+Math.floor(rng()*18),q={type,index:i,level,x,end:x+450,solved:false,progress:0,platforms:[],ground,alert:false,awareness:0};
 // Remove optional geometry and enemies that would obscure this authored encounter.
 w.platforms=w.platforms.filter(p=>p.ground||p.x+p.w<x||p.x>x+450);w.enemies=w.enemies.filter(e=>e.x<x-25||e.x>x+475);w.springs=w.springs.filter(s=>s.x<x-25||s.x>x+475);w.coins=w.coins.filter(c=>c.x<x||c.x>x+450);
 if(type==='cloud'){const count=4+Math.floor(level/2),gap=61+level*2;for(let k=0;k<count;k++){const f={x:x+k*gap,baseX:x+k*gap,y:242-Math.min(k,3)*37,w:65-level*5,cloudPuzzle:true,absent:0,standing:0,puzzleStep:k};q.platforms.push(f);}const last=q.platforms.at(-1);q.key={x:last.x+last.w/2,y:last.y-26};}
 if(type==='wind'){const n=level<3?2:3;q.fans=Array.from({length:n},(_,k)=>({x:x+28+k*112,y:249-k*53,dir:rng()<.35?-1:1,phase:rng()*Math.PI*2,used:false,active:false}));for(let k=0;k<n;k++)q.platforms.push({x:x+85+k*112,baseX:x+85+k*112,y:229-k*53,w:76-level*4,windPuzzle:true});const last=q.platforms.at(-1);q.key={x:last.x+last.w/2,y:last.y-26};}
 if(type==='guardian'){q.guardian={x:x+260,y:267,dir:-1,kind:'puff'};q.barrel={x:x+70,y:271,vx:0};q.key={x:x+320,y:255};q.guards=[];}
 w.platforms.push(...q.platforms);return q;});w.gate.x=4400;w.sign.x=4300;w.key.x=-9999;w.key.taken=true;return w.puzzles;}
function prepareExpeditionPuzzles(c){makeFreePuzzles(c.world);c.gateKeys=[];c.routeKey=false;c.gateOpen=false;c.message='Three key trials ahead. Read the signs; solve them in the world. No quiz screen.';c.messageUntil=9;}
const puzzleStartFree=startFreeWorld;startFreeWorld=function(index){const before=freeRun;puzzleStartFree(index);if(freeRun&&freeRun!==before){prepareExpeditionPuzzles(freeRun);updateFreeHUD();}};
function finishExpeditionPuzzle(q){if(q.solved)return;q.solved=true;freeRun.p.cheer=1;freeSpark(q.key.x,q.key.y,'#ffeda5');const count=freeRun.world.puzzles.filter(q=>q.solved).length;freeMessage(expeditionPuzzleTypes[q.type].name+' · KEY '+count+'/3',5);if(count===3){freeRun.routeKey=true;freeRun.gateOpen=true;freeMessage('ALL THREE TRIAL KEYS FOUND · The gate is open. Continue to the boss!',6);}}
function alertGuardian(q){if(q.alert||q.solved)return;q.alert=true;q.awareness=0;const w=freeRun.world;q.guards=[-95,100].map((dx,i)=>({x:q.guardian.x+dx,home:q.guardian.x+dx,y:270,dir:i? -1:1,hp:1,kind:w.def.enemy,phase:i,puzzleGuard:true}));w.enemies.push(...q.guards);freeMessage('ALERT! Two guards woke up. Defeat both, then USE the chest — or retry after respawning.',6);}
function puzzleHint(q){if(q.type==='cloud')return 'Land on clouds 1 → '+q.platforms.length+'. Each fades after 2 seconds standing. Falling to the ground resets the sequence; clouds return.';if(q.type==='wind')return 'USE near a fan to reverse it. Ride each right-facing gust in order, then land on the key altar. Watch ON / OFF.';return q.alert?'Defeat both alerted guards, then USE the chest.':'Do not attack the sleeper. Jump over it and USE from behind, or USE the barrel to roll it into the guardian.';}
const puzzleFreeInteract=freeInteract;freeInteract=function(){const c=freeRun;if(!c||c.paused||c.ended||c.quiz)return;const q=c.world.puzzles?.find(q=>!q.solved&&c.p.x>q.x-65&&c.p.x<q.end+50);if(q){if(q.type==='wind'){const fan=q.fans.find(f=>Math.abs(c.p.x-f.x)<48&&Math.abs(c.p.y-25-f.y)<75);if(fan){fan.dir*=-1;freeMessage(fan.dir===1?'Fan aimed RIGHT · Wait for the next gust.':'Fan aimed LEFT · USE again to aim toward the altar.',3);return;}}if(q.type==='guardian'){const b=q.barrel,g=q.guardian;if(Math.abs(c.p.x-b.x)<40&&!q.alert){b.vx=150;freeMessage('Barrel rolling — keep clear!',2);return;}if(!q.alert&&c.p.x>g.x+10&&c.p.x<q.key.x+35&&Math.abs(c.p.y-282)<40){finishExpeditionPuzzle(q);return;}if(q.alert&&q.guards.every(e=>e.hp<=0)&&Math.abs(c.p.x-q.key.x)<60){finishExpeditionPuzzle(q);return;}}freeMessage(puzzleHint(q),7);return;}if(Math.abs(c.p.x-c.world.gate.x)<110||Math.abs(c.p.x-c.world.sign.x)<70){const pending=c.world.puzzles?.find(q=>!q.solved);freeMessage(pending?'Missing key: '+expeditionPuzzleTypes[pending.type].name+' at '+Math.round(pending.x)+'m. Backtrack left.':'Gate open. Continue right to the boss.',7);return;}puzzleFreeInteract();};
const puzzleFreeAttack=freeAttack;freeAttack=function(){const c=freeRun;if(c&&!c.paused&&!c.ended&&!c.quiz&&c.p.attackCD<=0){for(const q of c.world.puzzles||[])if(q.type==='guardian'&&!q.solved&&Math.abs(c.p.x-q.guardian.x)<65&&Math.abs(c.p.y-25-q.guardian.y)<50)alertGuardian(q);}puzzleFreeAttack();};
for(const [id,fn]of [['free-attack',()=>freeAttack()],['free-interact',()=>freeInteract()]]){const b=document.getElementById(id);b.onpointerdown=e=>{e.preventDefault();fn();};b.onclick=e=>{if(e.detail===0)fn();};}
function updateExpeditionPuzzles(c,dt,after=false){const p=c.p;for(const q of c.world.puzzles||[]){if(q.solved)continue;if(q.type==='cloud'){if(!after){for(const f of q.platforms){f.absent=Math.max(0,f.absent-dt);if(f.absent===0&&f.standing>=2)f.standing=0;if(p.grounded&&p.floor===f){f.standing+=dt;if(f.standing>=2){f.absent=3.5;freeSpark(f.x+f.w/2,f.y,'#cee5f5');}}}}else{const landed=q.platforms.indexOf(p.floor);if(p.grounded&&landed===q.progress){q.progress++;freeSpark(p.x,p.y-5,'#d3f8e7');}if(p.grounded&&p.floor?.ground&&p.x>q.x-30&&p.x<q.end)q.progress=0;if(q.progress===q.platforms.length&&Math.hypot(p.x-q.key.x,p.y-25-q.key.y)<27)finishExpeditionPuzzle(q);}}
 if(q.type==='wind'&&!after){q.fans.forEach((f,i)=>{const cycle=3.7-q.level*.19;f.active=((c.time+f.phase)%cycle)<cycle*(.66-q.level*.035);if(f.active&&Math.abs(p.x-f.x)<49&&Math.abs(p.y-25-f.y)<76){p.x+=f.dir*(80+q.level*8)*dt;p.vy=Math.min(p.vy,-300);p.grounded=false;p.coyote=0;if(f.dir===1&&i===q.progress){f.used=true;q.progress++;}}});if(q.progress===q.fans.length&&Math.hypot(p.x-q.key.x,p.y-25-q.key.y)<28)finishExpeditionPuzzle(q);}
 if(q.type==='guardian'&&!after){const g=q.guardian,b=q.barrel;if(!q.alert){b.x+=b.vx*dt;if(b.vx&&Math.abs(b.x-g.x)<22){b.vx=0;finishExpeditionPuzzle(q);continue;}if(p.x<g.x&&g.x-p.x<55+q.level*5&&Math.abs(p.y-282)<28&&!p.duck){q.awareness+=dt;if(q.awareness>1.4-q.level*.13)alertGuardian(q);}else q.awareness=Math.max(0,q.awareness-dt*2);for(const shot of c.shots)if(Math.hypot(shot.x-g.x,shot.y-g.y)<28){shot.life=0;alertGuardian(q);}}else if(q.guards.some(e=>e.hp>0)&&Math.abs(p.x-g.x)<33&&Math.abs(p.y-282)<35)freeDamage();}
 }}
// Use the original exploration simulation, avoiding the superseded ground-key wrapper.
updateFree=function(dt){const c=freeRun;if(!c||c.paused||c.ended||c.quiz)return;updateExpeditionPuzzles(c,dt);trailFreeUpdate(dt);updateExpeditionPuzzles(c,dt,true);if(!c.gateOpen&&Math.abs(c.p.x-c.world.gate.x)<60){const q=c.world.puzzles.find(q=>!q.solved);if(q)freeMessage('Missing '+expeditionPuzzleTypes[q.type].name+' key · Backtrack to '+Math.round(q.x)+'m.',3);}};
const puzzleRespawn=freeRespawn;freeRespawn=function(){puzzleRespawn();const c=freeRun;for(const q of c.world.puzzles||[])if(!q.solved){q.progress=0;for(const f of q.platforms){f.absent=0;f.standing=0;}if(q.fans)for(const f of q.fans)f.used=false;if(q.type==='guardian'){c.world.enemies=c.world.enemies.filter(e=>!q.guards.includes(e));q.guards=[];q.alert=false;q.awareness=0;q.barrel.x=q.x+70;q.barrel.vx=0;}}};
const puzzlePlatform=retroPlatform;retroPlatform=function(g,f,kind){if(!f.cloudPuzzle){puzzlePlatform(g,f,kind);return;}if(f.absent>0)return;g.save();g.globalAlpha=1-Math.min(1,f.standing/2)*.65;puzzlePlatform(g,f,'cloud');g.fillStyle='#e7ba87';g.fillRect(f.x,f.y-5,f.w*(1-f.standing/2),2);retroText(g,String(f.puzzleStep+1),f.x+f.w/2,f.y+15,'#675579');g.restore();};
// The prior renderer already paints the world; add encounter-specific interactive props.
drawFree=function(){trailFreeDraw();const c=freeRun,g=freeG,t=motion.matches?0:c.time;g.save();g.translate(-Math.round(c.camera),0);for(const q of c.world.puzzles||[]){if(q.end<c.camera||q.x>c.camera+660)continue;retroBox(g,q.x-12,249,3,33,'#9c7993');retroBox(g,q.x-35,235,52,18,'#e8d6aa');retroText(g,(q.solved?'DONE':q.type==='cloud'?'CLOUD':q.type==='wind'?'WIND':'QUIET'),q.x-10,247,'#645475');if(q.type==='wind'){for(const f of q.fans){retroBox(g,f.x-2,f.y+5,4,28,'#8f7595');g.save();g.translate(Math.round(f.x),Math.round(f.y));g.rotate(t*(f.active?5:1)*f.dir);g.fillStyle=f.active?'#c4f2e3':'#a29cbb';for(let k=0;k<4;k++){g.fillRect(3,-3,19,6);g.rotate(Math.PI/2);}g.restore();retroText(g,(f.used?'OK ':f.active?'ON ':'OFF ')+(f.dir===1?'R':'L'),f.x,f.y-27);if(f.active&&!q.solved)for(let k=0;k<4;k++)retroBox(g,f.x+f.dir*((t*65+k*16)%65),f.y-12+k*8,8,1,'#d6f8ed');}}
 if(q.type==='guardian'){if(!q.solved){retroEnemy(g,q.guardian,t);retroText(g,q.alert?'! !':q.awareness>0?'?':'Z Z',q.guardian.x,q.guardian.y-27);}retroBox(g,q.barrel.x-10,262,20,20,'#91708b');retroBox(g,q.barrel.x-8,264,16,16,'#c49a72');retroBox(g,q.barrel.x-10,267,20,2,'#e7c794');retroBox(g,q.barrel.x-10,276,20,2,'#e7c794');retroBox(g,q.key.x-13,262,26,20,q.solved?'#88bb9f':'#bd936f');retroBox(g,q.key.x-2,269,4,5,'#ffe7aa');}else if(!q.solved){retroKey(g,q.key.x,q.key.y);retroText(g,q.progress+'/'+(q.type==='cloud'?q.platforms.length:q.fans.length),q.key.x,q.key.y-22);}}
 if(!c.gateOpen)retroText(g,c.world.puzzles.filter(q=>q.solved).length+'/3 TRIALS',c.world.gate.x+15,185);g.restore();};
const puzzleHUD=updateFreeHUD;updateFreeHUD=function(){puzzleHUD();const c=freeRun;if(!c?.world.puzzles)return;document.querySelector('#free-keys').textContent='TRIAL KEYS '+c.world.puzzles.filter(q=>q.solved).length+'/3 · '+(c.bossKey?'✓':'◇')+' BOSS KEY';const q=c.world.puzzles.find(q=>!q.solved&&c.p.x>q.x-80&&c.p.x<q.end+20);if(c.time>=c.messageUntil){const next=c.world.puzzles.find(q=>!q.solved);document.querySelector('#free-tip').textContent=q?expeditionPuzzleTypes[q.type].name+' · '+puzzleHint(q):next?'Next key trial: '+expeditionPuzzleTypes[next.type].name+' · '+Math.round(next.x)+'m · '+(next.x<c.p.x?'Backtrack left.':'Explore right.'):!c.bossKey?'Three trials complete. Continue right and defeat the weakpoint boss for the final key.':'All keys collected. Exit to the next world.';}};
