const freeRoot=document.createElement('section');freeRoot.id='free-adventure';freeRoot.hidden=true;
freeRoot.innerHTML=`<div id="free-select"><button id="free-back" class="fr-btn">← MODES</button><p class="fr-eyebrow">FREE MODE / EXPEDITION</p><h2>Choose your explorer</h2><p class="fr-subtitle">Five connected worlds. Hidden routes. Boss trials.</p><div id="free-roster"></div><div id="free-worlds"></div><p id="free-choice" role="status">Select a character and a world.</p><button id="free-start" class="fr-btn fr-primary" disabled>START EXPEDITION →</button><p class="fr-footnote">Around 3–5 minutes per world · No time limit · Progress saved between worlds</p></div>
<div id="free-play" hidden><canvas id="free-canvas" width="640" height="360" aria-label="Side-scrolling exploration game"></canvas><div class="fr-hud"><div><small id="free-world-label"></small><strong id="free-title"></strong><span id="free-health"></span></div><div class="fr-objectives"><span id="free-keys"></span><small id="free-coins"></small></div><button id="free-pause" class="fr-btn">Ⅱ PAUSE</button></div><div id="free-tip" role="status"></div><div id="free-boss-hud" hidden><strong id="free-boss-title"></strong><span id="free-boss-time"></span><div><i id="free-boss-progress"></i></div></div><div class="fr-map"><i id="free-map-position"></i><span>START</span><span>KEY</span><span>GATE</span><span>BOSS</span><span>EXIT →</span></div><div class="fr-controls"><div class="fr-dpad"><button data-free-key="left" aria-label="Move left">◀</button><button data-free-key="down" aria-label="Duck or brake">▼</button><button data-free-key="right" aria-label="Move right">▶</button></div><div class="fr-actions"><button id="free-interact">USE<small>E</small></button><button id="free-attack">ATTACK<small>J</small></button><button id="free-jump">JUMP<small>SPACE</small></button></div></div><div class="fr-key-guide">A/D MOVE · SPACE JUMP · J ATTACK · E INTERACT · S DUCK / BRAKE</div>
<div id="free-dialog" hidden role="dialog" aria-modal="true" aria-labelledby="free-dialog-title"><div class="fr-dialog-card"><p class="fr-eyebrow" id="free-dialog-tag">EXPEDITION</p><h2 id="free-dialog-title"></h2><p id="free-dialog-copy"></p><div id="free-answers"></div><p id="free-feedback" role="status"></p><div class="fr-dialog-buttons"><button id="free-resume" class="fr-btn fr-primary">CONTINUE</button><button id="free-next" class="fr-btn fr-primary" hidden>NEXT WORLD →</button><button id="free-retry" class="fr-btn" hidden>REPLAY WORLD</button><button id="free-exit" class="fr-btn">WORLD SELECT</button></div></div></div></div>`;
stage.append(freeRoot);
const freeCanvas=document.querySelector('#free-canvas'),freeG=freeCanvas.getContext('2d'),freeDialog=document.querySelector('#free-dialog');
let freeCharacter=null,freeWorldIndex=0,freeRun=null,freeLast=0;
const freeKeys=new Set(),freeTouches=new Map();
let freeRecords=Array(5).fill(null);
try{const data=JSON.parse(localStorage.getItem('fight-cute-free-v1')||'null');if(Array.isArray(data))freeRecords=freeRecords.map((_,i)=>data[i]&&Number.isFinite(data[i].time)&&data[i].time>0?{time:data[i].time}:null);}catch{}
function freeUnlocked(){let n=1;while(n<5&&freeRecords[n-1])n++;return n;}
function refreshFreeWorlds(){document.querySelector('#free-worlds').replaceChildren();freeWorlds.forEach((d,i)=>{const b=document.createElement('button');b.disabled=i>=freeUnlocked();b.className='fr-world';b.dataset.freeWorld=i;b.setAttribute('aria-pressed',String(i===freeWorldIndex));b.innerHTML=`<small>0${i+1} ${freeRecords[i]?'✓ COMPLETE':b.disabled?'· LOCKED':''}</small><strong>${d.name}</strong><span>${d.subtitle}</span>`;b.onclick=()=>{freeWorldIndex=i;refreshFreeWorlds();};document.querySelector('#free-worlds').append(b);});}
for(const [id,a] of Object.entries(animals)){const b=document.createElement('button');b.className='fr-character';b.dataset.freeCharacter=id;b.setAttribute('aria-pressed','false');b.innerHTML=`<canvas width="150" height="150" aria-hidden="true"></canvas><strong>${a.name}</strong>`;b.onclick=()=>{freeCharacter=id;document.querySelectorAll('.fr-character').forEach(q=>q.setAttribute('aria-pressed',String(q===b)));document.querySelector('#free-choice').textContent=a.name+' selected. All explorers share the same movement abilities.';document.querySelector('#free-start').disabled=false;};document.querySelector('#free-roster').append(b);}
function clearFreeInput(){freeKeys.clear();freeTouches.clear();document.querySelectorAll('[data-free-key]').forEach(b=>b.classList.remove('held'));}
function openFreeSelect(){clearFreeInput();freeRun=null;scene='free-select';modes.hidden=true;freeRoot.hidden=false;document.querySelector('#free-select').hidden=false;document.querySelector('#free-play').hidden=true;freeDialog.hidden=true;refreshFreeWorlds();document.querySelector('.fr-character').focus();}
window.addEventListener('fightcute:mode-selected',e=>{if(e.detail.mode==='free')openFreeSelect();});
document.querySelector('#free-back').onclick=()=>{freeRoot.hidden=true;freeRun=null;clearFreeInput();activate();};document.querySelector('#free-start').onclick=()=>startFreeWorld(freeWorldIndex);document.querySelector('#free-exit').onclick=openFreeSelect;
function startFreeWorld(index){if(!freeCharacter||index>=freeUnlocked())return;freeWorldIndex=index;const world=makeFreeWorld(index);const p=newFighter(freeCharacter,100,'player');Object.assign(p,{y:282,vx:0,vy:0,grounded:true,coyote:0,jumpBuffer:0,attackCD:0,springCD:0,duck:false});freeRun={world,p,camera:0,time:0,hearts:4,checkpoint:100,checkpointIndex:0,coins:0,paused:false,ended:false,quiz:false,routeKey:false,gateOpen:false,bossKey:false,hurt:0,deaths:0,shots:[],enemyShots:[],message:world.def.hint,messageUntil:8,boss:{x:6220,y:247,active:false,done:false,timer:0,fire:2,stagger:0,armor:6,nextSupply:12,supply:false},effects:[]};clearFreeInput();freeRoot.hidden=false;document.querySelector('#free-select').hidden=true;document.querySelector('#free-play').hidden=false;freeDialog.hidden=true;scene='free';document.querySelector('#free-title').textContent=world.def.name;document.querySelector('#free-world-label').textContent=`EXPEDITION / 0${index+1}`;document.querySelector('#free-pause').focus();updateFreeHUD();}
function freeMessage(text,seconds=4){freeRun.message=text;freeRun.messageUntil=freeRun.time+seconds;}
function freeModal(title,text,mode='pause'){clearFreeInput();freeDialog.hidden=false;document.querySelector('#free-dialog-title').textContent=title;document.querySelector('#free-dialog-copy').textContent=text;document.querySelector('#free-dialog-tag').textContent=mode==='win'?'WORLD CLEARED':mode==='quiz'?'RELAY TERMINAL':'EXPEDITION PAUSED';document.querySelector('#free-answers').replaceChildren();document.querySelector('#free-feedback').textContent='';document.querySelector('#free-resume').hidden=mode==='win'||mode==='quiz';document.querySelector('#free-next').hidden=mode!=='win'||freeWorldIndex===4;document.querySelector('#free-retry').hidden=mode!=='win';document.querySelector(mode==='win'?(freeWorldIndex===4?'#free-retry':'#free-next'):'#free-resume').focus();}
function pauseFree(){if(!freeRun||freeRun.ended||freeRun.quiz||freeRun.paused)return;freeRun.paused=true;freeModal('Take a break','Your current checkpoint and objectives will stay here.');}
document.querySelector('#free-pause').onclick=pauseFree;document.querySelector('#free-resume').onclick=()=>{freeRun.paused=false;freeRun.quiz=false;clearFreeInput();freeDialog.hidden=true;document.querySelector('#free-pause').focus();};document.querySelector('#free-next').onclick=()=>startFreeWorld(freeWorldIndex+1);document.querySelector('#free-retry').onclick=()=>startFreeWorld(freeWorldIndex);
function freeJump(){const c=freeRun;if(!c||scene!=='free'||c.paused||c.quiz||c.ended)return;c.p.jumpBuffer=.14;}
function freeAttack(){const c=freeRun;if(!c||scene!=='free'||c.paused||c.quiz||c.ended||c.p.attackCD>0)return;const p=c.p;p.attackCD=c.world.index===4?.35:.4;p.action={type:'attack',t:.1,duration:.32,windup:.09,range:60};if(c.world.index===4){c.shots.push({x:p.x+p.face*22,y:p.y-26,vx:p.face*330,life:1.5});}else{for(const e of c.world.enemies)if(e.hp>0&&Math.abs(e.x-p.x)<62&&(e.x-p.x)*p.face>=-10&&Math.abs(e.y-(p.y-22))<43){e.hp=0;freeSpark(e.x,e.y,'#ffe4a6');}if(c.boss.active&&!c.boss.done&&Math.abs(c.boss.x-p.x)<72)freeBossHit();}}
function freeBossHit(){const b=freeRun.boss;if(b.stagger>0)return;b.armor--;freeSpark(b.x,b.y,'#fff1ad');if(b.armor<=0){b.armor=6;b.stagger=5;freeMessage('Boss staggered for 5 seconds. Keep your distance!');}}
function freeSpark(x,y,color){for(let i=0;i<7;i++)freeRun.effects.push({x,y,vx:(i-3)*19,vy:-35-i%3*10,life:.45,color});}
function freeInteract(){const c=freeRun;if(!c||c.paused||c.quiz||c.ended)return;const p=c.p,w=c.world;
 if(Math.abs(p.x-w.sign.x)<70){freeMessage('Collect the amber key on the spring route and two glowing keys along the ground. The gate opens automatically.',8);return;}
 if(Math.abs(p.x-w.gate.x)<85&&!c.gateOpen){freeMessage('Collect all 3 gate keys. Follow the glowing key markers; no quiz needed.',5);return;}
 freeMessage('E reads signs and opens the logic gate. Jump to collect keys.');
}
function freeDamage(){const c=freeRun;if(!c||c.hurt>0||c.ended||c.paused||c.quiz)return;c.hearts--;c.hurt=1.6;c.p.vx=-c.p.face*120;c.p.vy=-140;freeSpark(c.p.x,c.p.y-25,'#ffd8d8');if(c.hearts<=0)freeRespawn();}
function freeRespawn(){const c=freeRun;c.deaths++;c.hearts=4;c.hurt=2;c.p.x=c.checkpoint;c.p.y=282;c.p.vx=0;c.p.vy=0;c.p.grounded=true;clearFreeInput();c.enemyShots=[];if(c.boss.active&&!c.boss.done){c.boss.timer=0;c.boss.armor=6;c.boss.fire=2;c.boss.stagger=0;c.boss.nextSupply=12;c.boss.supply=false;}c.camera=clamp(c.p.x-200,0,c.world.length-640);freeMessage(c.boss.active?'Boss trial restarted. Dodge, jump and attack to create openings.':'Checkpoint restored. Your keys and solved lock are kept.',5);}
function finishFreeWorld(){const c=freeRun;if(c.ended)return;if(!c.routeKey||!c.gateOpen||!c.bossKey){freeMessage('The exit needs the route key, solved lock and boss key.');return;}c.ended=true;const old=freeRecords[freeWorldIndex];if(!old||c.time<old.time)freeRecords[freeWorldIndex]={time:c.time};try{localStorage.setItem('fight-cute-free-v1',JSON.stringify(freeRecords));}catch{}freeModal(freeWorldIndex===4?'EXPEDITION COMPLETE':'WORLD CLEARED',`${c.world.def.name} · ${Math.floor(c.time/60)}m ${Math.floor(c.time%60)}s · ${c.coins} coins · ${c.deaths} checkpoint restarts. ${freeWorldIndex===4?'All five worlds mastered. Replay any world from the expedition map.':'Continue right into the next world, or return to world select.'}`,'win');}
function freeHeld(k){return freeKeys.has(k)||[...freeTouches.values()].includes(k);}
const freeKeyMap={a:'left',d:'right',s:'down',ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down'};
addEventListener('keydown',e=>{if(scene!=='free')return;if(!freeDialog.hidden){if(e.key==='Tab'){const bs=[...freeDialog.querySelectorAll('button')].filter(b=>!b.hidden&&!b.disabled);if(e.shiftKey&&document.activeElement===bs[0]){e.preventDefault();bs.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===bs.at(-1)){e.preventDefault();bs[0].focus();}}if(e.key==='Escape'&&!freeRun.quiz&&!freeRun.ended){e.preventDefault();document.querySelector('#free-resume').click();}return;}if(e.key==='Escape'){e.preventDefault();pauseFree();return;}if(freeKeyMap[e.key]){e.preventDefault();freeKeys.add(freeKeyMap[e.key]);}if(e.code==='Space'){e.preventDefault();if(!e.repeat)freeJump();}if(e.key.toLowerCase()==='j'&&!e.repeat)freeAttack();if(e.key.toLowerCase()==='e'&&!e.repeat)freeInteract();});
addEventListener('keyup',e=>freeKeys.delete(freeKeyMap[e.key]));addEventListener('blur',()=>{clearFreeInput();if(scene==='free')pauseFree();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&scene==='free')pauseFree();});
for(const b of document.querySelectorAll('[data-free-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);freeTouches.set(e.pointerId,b.dataset.freeKey);b.classList.add('held');};for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,e=>{freeTouches.delete(e.pointerId);b.classList.remove('held');});}
for(const [id,fn] of [['free-jump',freeJump],['free-attack',freeAttack],['free-interact',freeInteract]]){const b=document.getElementById(id);b.onpointerdown=e=>{e.preventDefault();fn();};b.onclick=e=>{if(e.detail===0)fn();};}
function updateFree(dt){
 const c=freeRun;if(!c||c.paused||c.ended||c.quiz)return;const p=c.p,w=c.world;c.time+=dt;c.hurt=Math.max(0,c.hurt-dt);p.land=Math.max(0,(p.land||0)-dt);p.cheer=Math.max(0,(p.cheer||0)-dt);p.attackCD=Math.max(0,p.attackCD-dt);p.springCD=Math.max(0,p.springCD-dt);p.jumpBuffer=Math.max(0,p.jumpBuffer-dt);if(p.action){p.action.t+=dt;if(p.action.t>=p.action.duration)p.action=null;}
 tickExpeditionDash(c,dt);
 const dx=Number(freeHeld('right'))-Number(freeHeld('left'));p.duck=freeHeld('down')&&p.grounded;
 for(const f of w.platforms){const old=f.x;if(f.move)f.x=f.baseX+Math.sin(c.time*1.2+f.baseX)*f.move;if(p.grounded&&p.floor===f)p.x+=f.x-old;}
 const ice=w.index===3&&p.grounded;const accel=p.duck?1100:ice?(dx?510:100):1300;const target=p.duck?0:dx*205;p.vx+=clamp(target-p.vx,-accel*dt,accel*dt);if(dx)p.face=dx;
 p.coyote=p.grounded?.12:Math.max(0,p.coyote-dt);if(p.jumpBuffer>0&&(p.grounded||p.coyote>0)){p.vy=w.jump;p.grounded=false;p.coyote=0;p.jumpBuffer=0;}
 if(p.dash>0)p.vx=p.face*390;
 const prev=p.y;p.x=clamp(p.x+p.vx*dt,22,w.length-22);p.vy+=w.gravity*dt;p.y+=p.vy*dt;p.grounded=false;p.floor=null;
 if(p.vy>=0)for(const f of w.platforms){if(f.absent>0)continue;if(p.x>=f.x-5&&p.x<=f.x+f.w+5&&prev<=f.y+1&&p.y>=f.y){if(p.vy>140)p.land=.16;p.y=f.y;p.vy=0;p.grounded=true;p.floor=f;break;}}
 if(!c.gateOpen&&p.x>w.gate.x-22&&p.x<w.gate.x+100){p.x=w.gate.x-22;p.vx=0;if(c.routeKey)freeMessage('Collect the two glowing keys on the path before this gate.');else freeMessage('Gate locked. Take the spring route to the amber key at 1,250m.',2);}
 if(p.grounded&&p.springCD<=0)for(const s of w.springs){if(Math.abs(p.x-s.x)<19&&Math.abs(p.y-s.y)<3){p.vy=w.index===2?-370:-470;p.grounded=false;p.springCD=.35;p.cheer=.6;freeSpark(s.x,s.y-8,'#b3f1e6');freeMessage('SPRING BOOST · Steer toward the upper ledge!',2);break;}}
 for(let i=0;i<w.checkpoints.length;i++){if(i>c.checkpointIndex&&p.x>=w.checkpoints[i]&&p.grounded&&!c.boss.active){c.checkpointIndex=i;c.checkpoint=w.checkpoints[i];c.hearts=4;freeMessage('Checkpoint reached · Health restored.',2.5);}}
 for(const coin of w.coins)if(!coin.taken&&Math.hypot(coin.x-p.x,coin.y-(p.y-23))<24){coin.taken=true;c.coins++;p.cheer=.35;freeSpark(coin.x,coin.y,'#ffe7a2');}
 if(!c.routeKey&&Math.hypot(w.key.x-p.x,w.key.y-(p.y-25))<29){c.routeKey=true;w.key.taken=true;freeSpark(w.key.x,w.key.y,'#fff1a7');freeMessage('AMBER KEY FOUND · Continue right to the logic gate.',5);}
 for(const e of w.enemies){if(e.hp<=0)continue;const floor=w.platforms.find(f=>f.ground&&e.home>=f.x&&e.home<f.x+f.w);e.x+=e.dir*(32+w.index*6)*dt;const low=Math.max(e.home-65,floor.x+18),high=Math.min(e.home+65,floor.x+floor.w-18);if(e.x<low){e.x=low;e.dir=1;}if(e.x>high){e.x=high;e.dir=-1;}e.y=270-(w.index===1?8+Math.sin(c.time*2+e.phase)*8:0);e.swing=(c.time+e.phase)%3;
  if(Math.abs(p.x-e.x)<25&&Math.abs((p.y-(p.duck?12:23))-e.y)<25){if(p.vy>30&&prev<e.y+5){e.hp=0;p.vy=-205;p.cheer=.5;freeSpark(e.x,e.y,'#f9e3a9');}else freeDamage();}
  if(e.kind==='ninja'&&e.swing>2.2&&e.swing<2.5&&Math.abs(e.x-p.x)<49&&(p.x-e.x)*e.dir>0&&Math.abs(p.y-282)<30&&!p.duck)freeDamage();
 }
 for(const q of c.shots){q.x+=q.vx*dt;q.life-=dt;for(const e of w.enemies)if(e.hp>0&&Math.hypot(q.x-e.x,q.y-e.y)<24){e.hp=0;q.life=0;freeSpark(e.x,e.y,'#ffe7a2');break;}if(c.boss.active&&!c.boss.done&&Math.hypot(q.x-c.boss.x,q.y-c.boss.y)<43){freeBossHit(q);q.life=0;}}c.shots=c.shots.filter(q=>q.life>0);
 const b=c.boss;
 updateWeakpointBoss(c,dt);
 for(const q of c.enemyShots){q.x+=q.vx*dt;q.life-=dt;if(Math.hypot(q.x-p.x,q.y-(p.y-(p.duck?10:25)))<(p.duck?15:22)){q.life=0;freeDamage();}}c.enemyShots=c.enemyShots.filter(q=>q.life>0&&q.x>w.bossStart-100&&q.x<w.bossEnd+100);
 if(b.done&&!c.bossKey&&Math.hypot(p.x-(w.bossEnd-70),p.y-25-249)<30){c.bossKey=true;freeSpark(p.x,p.y-25,'#aee6ce');freeMessage('MINT KEY SECURED · Exit to the next world →',5);}
 for(const fx of c.effects){fx.x+=fx.vx*dt;fx.y+=fx.vy*dt;fx.life-=dt;}c.effects=c.effects.filter(f=>f.life>0);
 if(p.y>440){freeRespawn();return;}
 c.camera+=(clamp(p.x-230,0,w.length-640)-c.camera)*Math.min(1,dt*7);
 if(p.x>w.exit&&p.grounded)finishFreeWorld();
}
function updateFreeHUD(){const c=freeRun;if(!c)return;document.querySelector('#free-health').textContent='♥ '.repeat(Math.max(0,c.hearts))+'♡ '.repeat(4-Math.max(0,c.hearts));document.querySelector('#free-keys').textContent=`${c.routeKey?'✓':'◇'} AMBER KEY    ${c.gateOpen?'✓':'◇'} LOCK    ${c.bossKey?'✓':'◇'} MINT KEY`;document.querySelector('#free-coins').textContent=`${c.coins} COINS · ${Math.floor(c.time/60)}:${String(Math.floor(c.time%60)).padStart(2,'0')} · 0${freeWorldIndex+1}/05`;document.querySelector('#free-tip').textContent=c.time<c.messageUntil?c.message:!c.routeKey?'Explore the upper route: use the teal spring to reach the amber key.':!c.gateOpen?'Collect the remaining glowing keys to open the gate.':!c.bossKey?'Read the boss tells, dodge, then attack its glowing weakpoint.':'Both keys collected. Exit to the next world →';document.querySelector('#free-map-position').style.left=clamp(c.p.x/c.world.length*100,0,100)+'%';document.querySelector('#free-boss-hud').hidden=!c.boss.active||c.boss.done;document.querySelector('#free-boss-title').textContent=c.world.def.boss+(c.boss.stagger>0?' · STAGGERED':'');document.querySelector('#free-boss-time').textContent=Math.max(0,Math.ceil(60-c.boss.timer))+'s TO KEY';document.querySelector('#free-boss-progress').style.width=Math.min(100,c.boss.timer/60*100)+'%';}
function drawFree(){
 const c=freeRun,w=c.world,g=freeG,t=motion.matches?0:c.time,cam=c.camera,d=w.def;g.imageSmoothingEnabled=false;
 const grad=g.createLinearGradient(0,0,0,360);grad.addColorStop(0,d.sky[0]);grad.addColorStop(1,d.sky[1]);g.fillStyle=grad;g.fillRect(0,0,640,360);
 const oval=(x,y,rx,ry,color)=>{const shading=g.createLinearGradient(x-rx,y-ry,x+rx,y+ry);shading.addColorStop(0,color);shading.addColorStop(1,color);g.fillStyle=shading;g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fill();};
 function cloud(x,y,s){oval(x,y,s,s*.2,'#d8e4f3');oval(x-12,y-6,s*.65,s*.23,'#f7fbff');oval(x+9,y-12,s*.48,s*.34,'#ffffff');}
 if(w.index===2){oval(510,65,36,36,'#f8f0db');oval(522,57,32,32,d.sky[0]);for(let i=0;i<48;i++){g.fillStyle=i%5?'#fff7e4':'#f5dea0';g.fillRect((i*91-cam*.04+10000)%680,15+i*43%215,i%5?1:2,2);}}
 else{oval(530,60,27,27,w.index===4?'#ffe1c3':'#fff0b8');for(let i=0;i<7;i++)cloud(((i*137-cam*.12+t*3)%850+850)%850-90,32+i*31%103,32+i%3*14);}
 // Far scenery and middle distance move at different speeds.
 if(w.index===0){for(let i=0;i<9;i++){const x=((i*166-cam*.16)%900+900)%900-120;oval(x,276,140,90+i%3*14,'#81c39d');oval(x+60,292,113,67,'#a3d4a5');}g.fillStyle='#6ebbb0';g.fillRect(0,273,640,15);}
 if(w.index===1){for(let i=0;i<9;i++)cloud(((i*117-cam*.2)%900+900)%900-100,235+i%3*27,65);}
 if(w.index===2){for(let i=0;i<6;i++){const x=((i*190-cam*.17)%1050+1050)%1050-100;oval(x,300,155,65,'#9c9dc7');oval(x+40,310,70,35,'#b0add0');}g.strokeStyle='#eef1ff66';g.lineWidth=1;g.beginPath();g.ellipse(520,65,56,8,-.2,0,7);g.stroke();}
 if(w.index===3){for(let i=0;i<7;i++){const x=((i*170-cam*.15)%1100+1100)%1100-100;g.fillStyle='#aacbdf';g.beginPath();g.moveTo(x-90,282);g.lineTo(x+20,72+i%3*25);g.lineTo(x+135,282);g.fill();g.fillStyle='#f5fdff';g.beginPath();g.moveTo(x-10,132+i%3*20);g.lineTo(x+20,72+i%3*25);g.lineTo(x+50,132+i%3*20);g.lineTo(x+20,120+i%3*20);g.fill();}}
 if(w.index===4){for(let i=0;i<8;i++){const x=((i*134-cam*.18)%1100+1100)%1100-80;g.fillStyle='#9c9bc6';g.fillRect(x,176,90,110);for(let j=0;j<3;j++){g.fillStyle='#666e9f';g.beginPath();g.moveTo(x-14,185-j*27);g.lineTo(x+45,164-j*27);g.lineTo(x+104,185-j*27);g.lineTo(x+96,193-j*27);g.lineTo(x-5,193-j*27);g.fill();}g.fillStyle='#f6d9b9';for(let j=0;j<4;j++)g.fillRect(x+12+j*17,215,7,20);}}
 // Distant observatories and faceted ruins establish scale behind the playable plane.
 for(let i=0;i<5;i++){const x=((i*213-cam*.28)%1150+1150)%1150-160;const y=240-i%2*26;g.fillStyle=['#477e83','#6a8ca8','#666d9b','#709eb4','#6a648d'][w.index];g.beginPath();g.moveTo(x,y);g.lineTo(x+48,y-18);g.lineTo(x+48,284);g.lineTo(x,284);g.fill();g.fillStyle='#19395344';g.beginPath();g.moveTo(x+48,y-18);g.lineTo(x+70,y-8);g.lineTo(x+70,284);g.lineTo(x+48,284);g.fill();g.fillStyle='#c5eddb88';g.fillRect(x+15,y+12,3,14);g.fillRect(x+30,y+7,3,14);g.fillStyle='#dfefdba0';g.fillRect(x+46,y-38,2,20);}
 g.save();g.translate(-cam,0);
 // Scenic props are separated from collision surfaces.
 for(let x=Math.floor(cam/210)*210-210;x<cam+850;x+=210){if(w.gaps.some(q=>x+20>q.x&&x<q.x+q.w))continue;
  if(w.index===0||w.index===4){g.fillStyle=w.index===4?'#947887':'#7e9a73';g.fillRect(x+28,196,8,87);oval(x+32,199,32,28,w.index===4?'#eab9d0':'#5fa87a');oval(x+15,183,26,23,w.index===4?'#f3c9dc':'#77bd83');oval(x+46,178,25,22,w.index===4?'#f8d6e3':'#95ce91');}
  else if(w.index===3){g.fillStyle='#78adc5';g.beginPath();g.moveTo(x,282);g.lineTo(x+19,241);g.lineTo(x+28,282);g.fill();g.fillStyle='#c7f0f6';g.beginPath();g.moveTo(x+13,282);g.lineTo(x+26,222);g.lineTo(x+40,282);g.fill();}
  else if(w.index===2){oval(x+20,283,30,8,'#8c8aaf');g.fillStyle='#a9a4c4';g.fillRect(x+5,270,15,12);g.fillStyle='#d7d1e7';g.fillRect(x+7,267,8,5);}
 }
 for(const f of w.platforms){if(f.x>cam+660||f.x+f.w<cam-20)continue;
  if(w.index===1){g.fillStyle='#b4c2e7';g.fillRect(f.x,f.y+3,f.w,19);for(let x=f.x+12;x<f.x+f.w;x+=25)oval(x,f.y+4,20,12,'#f6f9ff');g.fillStyle='#ffffff';g.fillRect(f.x,f.y-2,f.w,7);}
  else{g.fillStyle=d.ground[2];g.fillRect(f.x,f.y+5,f.w,f.ground?90:17);g.fillStyle=d.ground[1];g.fillRect(f.x,f.y,f.w,10);g.fillStyle=d.ground[0];g.fillRect(f.x,f.y-3,f.w,6);for(let x=Math.max(f.x,Math.floor(cam/16)*16);x<f.x+f.w&&x<cam+660;x+=16){g.fillStyle=d.ground[0];g.fillRect(x,f.y+3,6,4);if(f.ground){g.globalAlpha=.24;g.fillStyle='#fbecd3';g.fillRect(x+3,f.y+22+(x%3)*8,8,4);g.globalAlpha=1;}}}
  if(f.move){g.fillStyle='#689fb8';g.font='bold 10px monospace';g.textAlign='center';g.fillText('↔',f.x+f.w/2,f.y+8);}
 }
 for(const s of w.springs){if(s.x<cam-30||s.x>cam+670)continue;g.fillStyle='#506980';g.fillRect(s.x-17,s.y-3,34,5);g.strokeStyle='#cdeaf0';g.lineWidth=3;g.beginPath();for(let i=0;i<5;i++){g.lineTo(s.x+(i%2?-10:10),s.y-5-i*3);}g.stroke();g.fillStyle='#5ec5b7';g.fillRect(s.x-19,s.y-21,38,6);g.fillStyle='#baf2da';g.fillRect(s.x-17,s.y-22,34,3);g.fillStyle='#f6f0cc';g.font='bold 10px monospace';g.textAlign='center';g.fillText('↑',s.x,s.y-29);}
 for(const coin of w.coins)if(!coin.taken&&coin.x>cam-20&&coin.x<cam+660){oval(coin.x,coin.y+Math.sin(t*3+coin.x)*2,5,7,'#b88c45');oval(coin.x-1,coin.y-1+Math.sin(t*3+coin.x)*2,4,6,'#ffe0a0');}
 function key(x,y,color){g.strokeStyle=color;g.lineWidth=3;g.beginPath();g.arc(x-6,y,5,0,7);g.moveTo(x,y);g.lineTo(x+14,y);g.lineTo(x+14,y+4);g.moveTo(x+9,y);g.lineTo(x+9,y+4);g.stroke();}
 if(!c.routeKey){key(w.key.x,w.key.y+Math.sin(t*3)*2,'#fce1a3');g.fillStyle='#fff5d6';g.font='bold 9px monospace';g.textAlign='center';g.fillText('AMBER KEY',w.key.x,w.key.y-14);}
 // Signs and gate are readable landmarks, not background decoration.
 g.fillStyle='#6a7286';g.fillRect(w.sign.x-3,240,6,42);g.fillStyle='#fff0d0';g.fillRect(w.sign.x-29,225,58,28);g.fillStyle='#536679';g.font='bold 10px monospace';g.textAlign='center';g.fillText('CODE · E',w.sign.x,243);
 g.fillStyle='#576878';g.fillRect(w.gate.x-5,195,10,87);g.fillRect(w.gate.x+38,195,10,87);g.fillStyle=c.gateOpen?'#92d9bb':'#e6c38b';g.fillRect(w.gate.x-10,189,63,11);if(!c.gateOpen){g.fillStyle='#758399';g.fillRect(w.gate.x+4,204,34,78);g.fillStyle='#ecd1a0';g.fillRect(w.gate.x+15,228,12,17);}g.fillStyle='#fff6d8';g.font='bold 9px monospace';g.fillText(c.gateOpen?'UNLOCKED':'RELAY GATE',w.gate.x+20,182);
 for(const x of w.checkpoints){if(x<cam-30||x>cam+660)continue;g.fillStyle='#f4ead5';g.fillRect(x,250,2,32);g.fillStyle=x<=c.checkpoint?'#8bddbf':'#d9d9e0';g.fillRect(x+2,251,13,9);}
 for(const e of w.enemies)if(e.hp>0&&e.x>cam-60&&e.x<cam+700)drawFreeEnemy(g,e,t,false);
 const b=c.boss;if(b.x>cam-100&&b.x<cam+760){g.save();g.translate(b.x,b.y);g.scale(2.6,2.6);drawFreeEnemy(g,{x:0,y:0,kind:d.enemy,dir:b.x>c.p.x?-1:1,swing:c.time%3,hp:1},t,true);g.restore();if(b.active&&!b.done){g.fillStyle=b.fire<.65?'#ffe4a0':'#ffffffaa';g.font='bold 9px monospace';g.fillText(b.stagger>0?'STAGGERED':b.fire<.65?'INCOMING!':'',b.x,b.y-53);}}
 if(b.supply){g.fillStyle='#a9e6cf';g.fillRect(w.bossStart+74,240,12,18);g.fillRect(w.bossStart+71,244,18,10);g.fillStyle='#f6ffed';g.fillRect(w.bossStart+79,243,2,11);g.fillRect(w.bossStart+75,248,10,2);}
 if(b.active&&!b.done){g.fillStyle='#e8d79a66';g.fillRect(w.bossStart,198,3,84);g.fillRect(w.bossEnd,198,3,84);}if(b.done&&!c.bossKey)key(w.bossEnd-70,249+Math.sin(t*3)*2,'#b6f2d2');
 for(const q of c.enemyShots){oval(q.x,q.y,6,6,'#f2c887');oval(q.x-1,q.y-1,3,3,'#fff4cf');}
 for(const q of c.shots){g.save();g.translate(q.x,q.y);g.rotate(t*15);g.fillStyle='#eff7fa';g.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?3:9;g.lineTo(Math.cos(a)*r,Math.sin(a)*r);}g.closePath();g.fill();oval(0,0,2,2,'#6c8396');g.restore();}
 g.fillStyle='#556879';g.fillRect(w.exit,206,7,76);g.fillRect(w.exit+53,206,7,76);g.fillStyle='#afdcc9';g.fillRect(w.exit-5,198,70,12);g.fillStyle='#fff0ce';g.font='bold 11px monospace';g.fillText(w.index===4?'FINISH':'NEXT →',w.exit+28,187);
 const p=c.p;g.save();g.translate(p.x,p.y);g.scale(.62,p.duck?.43:.62);g.translate(0,-groundY);if(c.hurt>0)g.globalAlpha=.45+.55*Math.sin(c.time*22)**2;drawFighter(g,{...p,x:0,y:groundY,hideLabel:true,airborne:!p.grounded},t);
 if(w.index===4){g.save();g.translate(0,groundY);g.scale(p.face,1);g.fillStyle='#465777';g.fillRect(-17,-30,34,19);g.fillStyle='#9dd9cf';g.fillRect(-17,-17,34,4);g.fillStyle='#405170';g.fillRect(-30,-68,62,5);g.beginPath();g.moveTo(-28,-65);g.lineTo(-48,-57+Math.sin(t*8)*3);g.lineTo(-33,-70);g.fill();g.fillStyle='#d9e9e6';g.fillRect(15,-67,8,3);g.restore();}g.restore();
 for(const fx of c.effects){g.globalAlpha=Math.min(1,fx.life*3);g.fillStyle=fx.color;g.fillRect(fx.x,fx.y,2,2);}g.globalAlpha=1;g.restore();
 if(w.index===3||w.index===4){g.fillStyle=w.index===3?'#ffffffaa':'#f5c9ddaa';for(let i=0;i<20;i++)g.fillRect((i*83+t*12)%650,(i*43+t*19)%350,2,2);}
}
function drawFreeEnemy(g,e,t,boss=false){
 const ellipse=(x,y,rx,ry,color)=>{g.fillStyle=color;g.beginPath();g.ellipse(x,y,rx,ry,0,0,7);g.fill();};g.save();g.translate(e.x,e.y);
 if(e.kind==='spider'){g.strokeStyle='#617080';g.lineWidth=2;for(const side of [-1,1])for(let i=0;i<3;i++){g.beginPath();g.moveTo(side*8,-1+i*3);g.lineTo(side*(16+i*2),-8+i*5+Math.sin(t*8+i)*2);g.lineTo(side*(20+i*2),7+i);g.stroke();}ellipse(0,0,12,10,boss?'#69849b':'#8793aa');ellipse(-2,-3,6,4,'#a5b8c7');}
 else if(e.kind==='puff'||e.kind==='moonbug'){for(const side of [-1,1])ellipse(side*13,-6+Math.sin(t*9)*3,9,4,'#e6e5f4');ellipse(0,0,13,11,e.kind==='puff'?'#bacce4':'#bdb0d5');if(e.kind==='moonbug'){g.strokeStyle='#dddbf0';g.lineWidth=2;g.beginPath();g.moveTo(-5,-8);g.lineTo(-9,-17);g.moveTo(5,-8);g.lineTo(9,-17);g.stroke();}}
 else if(e.kind==='snowling'){ellipse(0,-1,12,15,'#e7f2f5');ellipse(0,-2,8,10,'#a7c7d8');ellipse(-7,11,5,3,'#7191ac');ellipse(7,11,5,3,'#7191ac');}
 else{ellipse(0,-2,12,13,'#62738c');g.fillStyle='#bfd9df';g.fillRect(-9,-7,18,7);g.fillStyle='#99cfc4';g.fillRect(-10,7,20,3);g.strokeStyle=e.swing>1.7?'#fff1b4':'#e4e9ed';g.lineWidth=2;g.beginPath();g.moveTo(e.dir*10,1);g.lineTo(e.dir*(e.swing>2.2?34:15),e.swing>2.2?1:-22);g.stroke();}
 g.fillStyle='#344656';g.fillRect(-5,-4,2,3);g.fillRect(4,-4,2,3);if(boss){g.fillStyle='#f0d395';g.fillRect(-8,-15,16,3);g.fillRect(-8,-20,3,6);g.fillRect(-1,-22,3,7);g.fillRect(5,-20,3,6);}g.restore();
}
function freeFrame(now){const dt=Math.min(.025,(now-freeLast)/1000||.016);freeLast=now;if(scene==='free-select'){for(const b of document.querySelectorAll('.fr-character')){const cvs=b.querySelector('canvas'),g=cvs.getContext('2d');g.clearRect(0,0,150,150);g.save();g.translate(75,140-groundY);drawFighter(g,{...newFighter(b.dataset.freeCharacter,0,'player'),hideLabel:true},motion.matches?0:now/1000);g.restore();}}if(scene==='free'&&freeRun){updateFree(dt);drawFree();updateFreeHUD();}requestAnimationFrame(freeFrame);}requestAnimationFrame(freeFrame);
