/* Portrait-only handheld shell. Existing control nodes retain their listeners. */
const handheld=document.createElement('div');handheld.id='handheld-shell';handheld.setAttribute('aria-hidden','true');handheld.innerHTML='<div class="hh-brand"><i></i>FIGHT CUTE <span>POCKET</span></div><div class="hh-screen"><div class="hh-glare"></div></div><div class="hh-divider"><b>⊕</b><i></i><span>PLAY YOUR WORLD</span><i></i><b>⊕</b></div>';
const handheldDock=document.createElement('section');handheldDock.id='handheld-dock';handheldDock.setAttribute('aria-label','Handheld game controls');handheldDock.innerHTML='<div class="hh-tools"></div><div class="hh-controls"><div class="hh-left"></div><div class="hh-right"></div></div><div class="hh-menu"></div>';
document.querySelector('main').append(handheld,handheldDock);
const handheldHomes=new Map();let handheldMode='',handheldSignature='',handheldPortrait=false;
function restoreHandheld(){for(const [node,anchor]of handheldHomes){anchor.replaceWith(node);}handheldHomes.clear();}
function dockExisting(selector,target){const node=document.querySelector(selector);if(!node)return;const anchor=document.createComment('handheld control home');node.replaceWith(anchor);handheldHomes.set(node,anchor);handheldDock.querySelector(target).append(node);}
function handheldLayout(){const portrait=innerWidth<innerHeight;handheldPortrait=portrait;document.documentElement.classList.toggle('handheld',portrait);if(portrait){const r=handheld.querySelector('.hh-screen').getBoundingClientRect(),s=Math.min((r.width-12)/1280,(r.height-12)/720);stage.style.setProperty('--scale',s);stage.style.left=(r.left+r.width/2)+'px';stage.style.top=(r.top+r.height/2)+'px';canvas.style.cssText=`left:${r.left+6}px;top:${r.top+6}px;width:${r.width-12}px;height:${r.height-12}px`;canvas.width=Math.ceil((r.width-12)/(s*4));canvas.height=Math.ceil((r.height-12)/(s*4));ctx.imageSmoothingEnabled=false;}else{stage.style.left='';stage.style.top='';canvas.style.cssText='';}handheldMode='';updateHandheld();}
addEventListener('resize',()=>{resetArenaInput();clearFreeInput();clearChallengeInput();handheldLayout();});
function updateHandheld(){const paused=scene==='battle'?(match?.paused||match?.ended):scene==='free'?(freeRun?.paused||freeRun?.ended||freeRun?.quiz):scene==='challenge'?(challengeRun?.paused||challengeRun?.ended||challengeRun?.quiz):true;const mode=handheldPortrait?(!paused&&['battle','free','challenge'].includes(scene)?scene:'menu'):'off';
 if(mode!==handheldMode){restoreHandheld();handheldDock.querySelectorAll('.hh-tools,.hh-left,.hh-right,.hh-menu').forEach(n=>n.replaceChildren());handheldMode=mode;handheldSignature='';handheldDock.dataset.mode=mode;if(mode==='battle'){dockExisting('#joystick','.hh-left');dockExisting('#dodge-btn','.hh-left');for(const id of ['attack-btn','heavy-btn','guard-btn','skill-btn','jump-btn','ultimate-btn'])dockExisting('#'+id,'.hh-right');dockExisting('#match-pause','.hh-tools');}else if(mode==='free'){dockExisting('.fr-dpad','.hh-left');dockExisting('#free-dash','.hh-left');for(const id of ['free-attack','free-jump','free-interact'])dockExisting('#'+id,'.hh-right');dockExisting('#free-pause','.hh-tools');}else if(mode==='challenge'){dockExisting('.ch-pad','.hh-left');dockExisting('#ch-dash','.hh-left');for(const id of ['ch-bop','ch-jump','ch-use'])dockExisting('#'+id,'.hh-right');dockExisting('#ch-pause','.hh-tools');}}
 if(mode==='menu'){
 const modal=[...stage.querySelectorAll('[role=dialog]')].find(n=>n.getClientRects().length&&!n.closest('[hidden]'));const buttons=[...(modal||stage).querySelectorAll('button')].filter(b=>b.getClientRects().length&&!b.closest('[hidden]')&&getComputedStyle(b).visibility!=='hidden');
 const signature=scene+buttons.map(b=>b.id+b.textContent+b.disabled+b.getAttribute('aria-pressed')).join('|');
 if(signature!==handheldSignature){handheldSignature=signature;const menu=handheldDock.querySelector('.hh-menu');menu.replaceChildren();for(const source of buttons){const b=document.createElement('button');b.type='button';b.textContent=source.id==='start'?'START GAME':source.getAttribute('aria-label')||source.textContent.trim().replace(/\s+/g,' ');b.disabled=source.disabled;b.setAttribute('aria-pressed',source.getAttribute('aria-pressed')||'false');b.onclick=()=>{source.click();handheldSignature='';updateHandheld();};menu.append(b);}}
 }
}
function handheldTick(){updateHandheld();requestAnimationFrame(handheldTick);}handheldLayout();requestAnimationFrame(handheldTick);
