/* Exploration gates: collect visible keys in the world; no terminal or quiz. */
function challengeGateKeys(c){for(const gate of c.course.gates){if(!gate.keys){const p=c.course.platforms.find(p=>p.y===gate.y&&gate.x>=p.x&&gate.x<=p.x+p.w);gate.keys=[.2,.5,.8].map(n=>({x:p.x+p.w*n,y:p.y-25,taken:false}));}}}
function freeGateKeys(c){c.gateKeys??=[{x:2100,y:257,taken:false},{x:2230,y:257,taken:false}];return c.gateKeys;}
function touchTrailKey(p,k){return Math.abs(p.x-k.x)<19&&Math.abs(p.y-25-k.y)<31;}
function paintTrailKey(g,k,t){if(k.taken)return;const y=k.y+(motion.matches?0:Math.sin(t*3+k.x)*2);g.save();g.fillStyle='#ffef9d30';g.fillRect(Math.round(k.x)-11,Math.round(y)-11,22,22);retroKey(g,k.x,y);g.restore();}
const trailChallengeUpdate=updateChallenge;updateChallenge=function(dt){const c=challengeRun;if(c&&!c.paused&&!c.ended){challengeGateKeys(c);for(const gate of c.course.gates){if(gate.solved)continue;for(const key of gate.keys)if(!key.taken&&touchTrailKey(c.p,key)){key.taken=true;c.p.cheer=.3;c.message='GATE KEYS '+gate.keys.filter(k=>k.taken).length+'/3';c.messageUntil=c.time+2;}if(gate.keys.every(k=>k.taken)){gate.solved=true;c.p.cheer=1;c.message='GATE OPEN! Keep exploring.';c.messageUntil=c.time+3;}}}trailChallengeUpdate(dt);};
const trailChallengeDraw=drawChallenge;drawChallenge=function(){trailChallengeDraw();const c=challengeRun;challengeGateKeys(c);chG.save();chG.translate(0,-Math.round(c.camera));for(const gate of c.course.gates)if(!gate.solved){for(const key of gate.keys)paintTrailKey(chG,key,c.time);retroText(chG,gate.keys.filter(k=>k.taken).length+'/3 KEYS',gate.x,gate.y-59);}chG.restore();};
const trailFreeUpdate=updateFree;updateFree=function(dt){const c=freeRun;if(c&&!c.paused&&!c.ended){for(const key of freeGateKeys(c))if(!key.taken&&touchTrailKey(c.p,key)){key.taken=true;freeSpark(key.x,key.y,'#ffe599');freeMessage('GATE KEYS '+(Number(c.routeKey)+c.gateKeys.filter(k=>k.taken).length)+'/3',3);}if(!c.gateOpen&&c.routeKey&&c.gateKeys.every(k=>k.taken)){c.gateOpen=true;freeMessage('GATE OPEN! Continue right to the boss trial.',5);}}trailFreeUpdate(dt);};
const trailFreeDraw=drawFree;drawFree=function(){trailFreeDraw();const c=freeRun;freeG.save();freeG.translate(-Math.round(c.camera),0);for(const key of freeGateKeys(c))paintTrailKey(freeG,key,c.time);if(!c.gateOpen)retroText(freeG,(Number(c.routeKey)+c.gateKeys.filter(k=>k.taken).length)+'/3 KEYS',c.world.gate.x+15,185);freeG.restore();};
const trailFreeHUD=updateFreeHUD;updateFreeHUD=function(){trailFreeHUD();const c=freeRun;if(!c)return;const n=Number(c.routeKey)+freeGateKeys(c).filter(k=>k.taken).length;document.querySelector('#free-keys').textContent='GATE KEYS '+n+'/3    '+(c.bossKey?'✓':'◇')+' BOSS KEY';};
