/* Ten randomized relay minigames. One lifecycle owns all timers and input. */
const relayCatalog=[['Signal Matrix I','Restore the signal to release the gate.'],['Wire Reroute','Match the currents. Cross none.'],['Power Calibration','Hold steady. Strike on the mark.'],['Signal Matrix II',"Some circuits won't budge. Plan around them."],['Echo Sequence','Listen. Then answer in kind.'],['Dual Relay Sync','Two terminals, one signal. Balance both.'],['Dial Alignment','Align the frequencies. They resist alone.'],['Interference Sweep','Clear the noise before it spreads.'],['Signal Matrix III','Remember the pattern. The grid forgets first.'],['Master Relay (Boss)',"Every circuit you've mastered, now as one."]];
let activeRelayGame=null,relaySoundContext=null;
const relayRandom=n=>Math.floor(Math.random()*n);
function relayToggleModel(type){const n=type===4?4:type===9?5:type===6?2:3,count=type===6?8:n*n,locked=new Set(),cells=Array(count).fill(0),moves=[];if(type===4)while(locked.size<1+relayRandom(2))locked.add(relayRandom(count));function affected(i){if(locked.has(i))return[];if(type===6){const base=i<4?0:4,k=i%4;return [i,base+(k^1),base+(k^2),(i+4)%8];}const x=i%n,y=Math.floor(i/n);return[i,...(x?[i-1]:[]),...(x<n-1?[i+1]:[]),...(y?[i-n]:[]),...(y<n-1?[i+n]:[])].filter(k=>!locked.has(k));}function turn(i){for(const j of affected(i))cells[j]^=1;}for(let k=0;k<(type===9?9:type===1?5:8);k++){let i;do{i=relayRandom(count);}while(locked.has(i));turn(i);moves.push(i);}if(cells.every(v=>!v)){const i=cells.findIndex((v,i)=>!locked.has(i));turn(i);moves.push(i);}return{type,n,cells,locked,moves,turn,initial:[...cells]};}
function relayTone(i){if(typeof musicEnabled!=='undefined'&&!musicEnabled)return;try{relaySoundContext??=new (window.AudioContext||window.webkitAudioContext)();relaySoundContext.resume();const o=relaySoundContext.createOscillator(),v=relaySoundContext.createGain(),t=relaySoundContext.currentTime;o.type='triangle';o.frequency.value=[330,440,554,660][i%4];v.gain.setValueAtTime(.035,t);v.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(v);v.connect(relaySoundContext.destination);o.start();o.stop(t+.21);}catch{}}
mountRelayPuzzle=function(host,seed,difficulty,onSolved,onAssist=()=>{}){
 activeRelayGame?.dispose();const free=host.id==='free-answers',type=free?1+relayRandom(10):clamp(difficulty,1,10);let alive=true,done=false,time=0,last=performance.now(),raf=0,update=null,stageIndex=0,stageType=type,model=null;
 const chain=type===10?[1,2,7]:[type];host.replaceChildren();host.className='relay-host relay-suite';
 const title=document.createElement('h3'),caption=document.createElement('p'),instructions=document.createElement('p'),area=document.createElement('div'),status=document.createElement('p'),actions=document.createElement('div');title.className='relay-game-title';caption.className='relay-game-caption';instructions.className='relay-instruction';area.className='relay-game-area';status.className='relay-status';status.setAttribute('role','status');actions.className='relay-actions';host.append(title,caption,instructions,area,status,actions);
 const session={type,get disposed(){return !alive;},get model(){return model;},dispose(){alive=false;cancelAnimationFrame(raf);update=null;}};host._relay=session;activeRelayGame=session;
 function say(s){status.textContent=s;}function button(label,fn,parent=actions){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{if(alive&&!done)fn();};parent.append(b);return b;}
 function win(){if(!alive||done)return;update=null;if(stageIndex<chain.length-1){stageIndex++;say('Stage complete. Continue the relay chain.');actions.replaceChildren();button('NEXT CIRCUIT',build).focus();area.querySelectorAll('button').forEach(b=>b.disabled=true);return;}done=true;area.querySelectorAll('button').forEach(b=>b.disabled=true);actions.replaceChildren();say('SYSTEM ONLINE · Gate unlocked.');cancelAnimationFrame(raf);onSolved();}
 function retry(){onAssist();build();}
 function build(){if(!alive)return;stageType=chain[stageIndex];area.replaceChildren();actions.replaceChildren();update=null;time=0;title.textContent=relayCatalog[type-1][0]+(type===10?' · '+(stageIndex+1)+'/3':'');caption.textContent=relayCatalog[type-1][1];say('');if([1,4,6,9].includes(stageType))matrix();else if(stageType===2)wires();else if(stageType===3)calibration();else if(stageType===5)echo();else if(stageType===7)dials();else if(stageType===8)sweep();host.querySelector('button:not(:disabled)')?.focus();}
 function matrix(){model=relayToggleModel(stageType);const m=model,history=[];let revealUntil=stageType===9?3:Infinity;instructions.textContent=stageType===6?'Flip a cell, its two neighbours and the matching cell in the other terminal. Switch ALL eight off.':stageType===9?'Study the lit cells for 3 seconds, then switch the hidden grid OFF. A click flips itself and neighbours.':'Switch all cells OFF. Click a cell to flip itself and its direct neighbours.'+(stageType===4?' LOCKED cells never change and cannot be pressed.':'');
 const wrap=document.createElement('div');wrap.className=stageType===6?'relay-dual':'relay-single';area.append(wrap);const buttons=[];for(let group=0;group<(stageType===6?2:1);group++){const board=document.createElement('div');board.className='relay-board';board.style.setProperty('--columns',m.n);wrap.append(board);for(let k=0;k<(stageType===6?4:m.cells.length);k++){const i=group*4+k,b=button('',()=>{m.turn(i);history.push(i);paint();if(m.cells.every(v=>v===0))win();},board);b.className='relay-cell';buttons[i]=b;}}
 function paint(){const hidden=time>=revealUntil;buttons.forEach((b,i)=>{const locked=m.locked.has(i);b.disabled=locked;b.textContent=locked?'X':hidden?'?':m.cells[i]?'◆':'·';b.dataset.state=hidden?'hidden':String(m.cells[i]);b.setAttribute('aria-label',`Cell ${i+1}, ${locked?'locked':hidden?'hidden':m.cells[i]?'on':'off'}`);});say(stageType===9?(hidden?'PATTERN HIDDEN · '+history.length+' moves':'MEMORIZE · '+Math.ceil(revealUntil-time)+'s'):history.length+' moves · '+m.cells.filter(Boolean).length+' active');}
 button('UNDO',()=>{if(history.length){m.turn(history.pop());paint();}});button('RESET',()=>{m.cells.splice(0,m.cells.length,...m.initial);history.length=0;revealUntil=stageType===9?time+3:Infinity;onAssist();paint();});button(stageType===9?'REVEAL 3s':'HINT',()=>{onAssist();if(stageType===9){revealUntil=time+3;paint();}else say(stageType===6?'Each click also flips its corresponding cell on the other board. Track both together.':stageType===4?'Locked cells are excluded from every toggle. Undo a move to compare its exact neighbours.':'Work from top to bottom: flip below a lit cell. Try a different first-row pattern if the bottom stays on.');});if(stageType===9)update=paint;paint();}
 function wires(){const rot=relayRandom(4),transform=i=>{let x=i%5,y=Math.floor(i/5);for(let k=0;k<rot;k++)[x,y]=[4-y,x];return y*5+x;};const routes=[[0,1,6,7,12],[4,3,8,13,18,19,24],[20,21,16,17,22,23]].map(a=>a.map(transform)),paths=[[],[],[]],colors=['#ae537c','#487eae','#668b4c'];const labels=[1+relayRandom(3),4+relayRandom(3),7+relayRandom(3)];let current=-1,drag=false;model={type:2,routes,paths,labels};instructions.textContent='Drag from one numbered node to its matching node. Use adjacent squares; no overlaps. You can also click each square, or use Tab + Enter.';const board=document.createElement('div');board.className='relay-board wire-board';board.style.setProperty('--columns',5);area.append(board);const cells=[];const endpoint=i=>routes.findIndex(a=>a[0]===i||a.at(-1)===i);
 function paint(){cells.forEach((b,i)=>{const ep=endpoint(i),owner=paths.findIndex(p=>p.includes(i));b.textContent=ep>=0?labels[ep]:owner>=0?'■':'·';b.style.background=owner>=0||ep>=0?colors[ep>=0?ep:owner]:'';b.style.color=owner>=0||ep>=0?'#fff5df':'';b.setAttribute('aria-label',`Square ${i+1}${ep>=0?', node '+labels[ep]:''}`);});say(paths.filter((p,j)=>p.length>1&&endpoint(p.at(-1))===j&&p.at(-1)!==p[0]).length+'/3 currents connected');}
 function visit(i,start=false){const ep=endpoint(i);if(start&&ep>=0){current=ep;paths[ep]=[i];paint();return;}if(current<0)return;const p=paths[current],last=p.at(-1);if(i===last)return;if(Math.abs(i%5-last%5)+Math.abs(Math.floor(i/5)-Math.floor(last/5))!==1)return;if(paths.some((q,j)=>j!==current&&q.includes(i))||(ep>=0&&ep!==current)){say('Wires cannot cross another current.');return;}if(p.length>1&&i===p[p.length-2])p.pop();else if(!p.includes(i))p.push(i);if(ep===current&&i!==p[0])current=-1;paint();if(paths.every((q,j)=>q.length>1&&endpoint(q.at(-1))===j&&q.at(-1)!==q[0]))win();}
 for(let i=0;i<25;i++){const b=button('',()=>visit(i),board);b.className='relay-cell';b.dataset.wireCell=i;b.onclick=e=>{if(e.detail===0&&alive&&!done)visit(i,current<0&&endpoint(i)>=0);};cells.push(b);}board.onpointerdown=e=>{const b=e.target.closest('[data-wire-cell]');if(!b)return;e.preventDefault();drag=true;board.setPointerCapture(e.pointerId);const i=+b.dataset.wireCell;visit(i,endpoint(i)>=0&&(current<0||endpoint(i)!==current||i===paths[current][0]));};board.onpointermove=e=>{if(!drag)return;const b=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-wire-cell]');if(b&&board.contains(b))visit(+b.dataset.wireCell);};board.onpointerup=()=>drag=false;board.onpointercancel=()=>drag=false;button('CLEAR WIRES',()=>{paths.forEach(p=>p.length=0);current=-1;paint();});button('HINT',()=>{onAssist();say('Start near an edge. Leave open squares around the inner node. Wires need not fill the whole board.');});paint();}
 function calibration(){let hits=0,center=.25+Math.random()*.5;const speed=.65+Math.random()*.4;model={type:3,hits:0,position:0,center,width:.18};instructions.textContent='Stop the cursor inside the green zone three times. Missing resets your streak; there is no retry limit.';const track=document.createElement('div');track.className='relay-meter';track.innerHTML='<i class="relay-target"></i><b class="relay-cursor"></b>';area.append(track);const target=track.firstChild,cursor=track.lastChild;function targetPaint(){target.style.left=(center-.09)*100+'%';target.style.width='18%';model.center=center;}targetPaint();button('CALIBRATE',()=>{if(Math.abs(model.position-center)<=.09){hits++;model.hits=hits;if(hits===3){win();return;}center=.25+Math.random()*.5;targetPaint();say(hits+'/3 calibrated');}else{hits=0;model.hits=0;onAssist();say('Missed the zone. Try again · 0/3');}},area).className='relay-trigger';update=()=>{model.position=(Math.sin(time*speed*3)+1)/2;cursor.style.left=model.position*100+'%';};say('0/3 calibrated');}
 function echo(){const sequence=Array.from({length:4+relayRandom(3)},()=>relayRandom(4));let playing=false,start=0,index=0,lastFlash=-1;model={type:5,sequence,input:[],playing:false};instructions.textContent='Press PLAY, watch the numbered lights, then repeat the sequence. Sound is optional; every note has a visible cue.';const board=document.createElement('div');board.className='relay-board echo-board';board.style.setProperty('--columns',2);area.append(board);const pads=[];function play(){playing=true;model.playing=true;start=time;index=0;model.input=[];lastFlash=-1;say('WATCH · '+sequence.length+' notes');}for(let i=0;i<4;i++){const b=button(String(i+1),()=>{if(playing)return;relayTone(i);if(i!==sequence[index]){onAssist();say('Sequence missed. Press PLAY to watch again.');index=0;model.input=[];return;}model.input.push(i);index++;say(index+'/'+sequence.length+' repeated');if(index===sequence.length)win();},board);b.className='relay-cell echo-pad';b.dataset.pad=i;pads.push(b);}button('PLAY / REPLAY',play);update=()=>{if(!playing)return;const elapsed=time-start,step=Math.floor(elapsed/.75);pads.forEach(b=>{b.classList.remove('lit');b.disabled=true;});if(step>=sequence.length){playing=false;model.playing=false;pads.forEach(b=>b.disabled=false);say('YOUR TURN · Repeat '+sequence.length+' notes');return;}if(elapsed%.75<.46)pads[sequence[step]].classList.add('lit');if(step!==lastFlash){lastFlash=step;relayTone(sequence[step]);}};pads.forEach(b=>b.disabled=true);say('Press PLAY when ready');}
 function dials(){const target=Array.from({length:3},()=>relayRandom(8)),values=[...target],moves=Array.from({length:5+relayRandom(4)},()=>relayRandom(3));function turn(i){values[i]=(values[i]+1)%8;values[(i+1)%3]=(values[(i+1)%3]+1)%8;}moves.forEach(turn);if(values.every((v,i)=>v===target[i])){turn(0);moves.push(0);}model={type:7,target,values,moves,window:false};instructions.textContent='Match each dial to its marked number (0–7). A turn also shifts the next dial. Press a dial only while SYNC is green.';const row=document.createElement('div');row.className='relay-dials';area.append(row);const buttons=[];const lamp=document.createElement('p');lamp.className='relay-sync';area.append(lamp);function paint(){buttons.forEach((b,i)=>{b.innerHTML='<small>TARGET '+target[i]+'</small><span style="transform:rotate('+values[i]*45+'deg)">↑</span><strong>'+values[i]+'</strong>';b.setAttribute('aria-label','Dial '+(i+1)+', current '+values[i]+', target '+target[i]);});}for(let i=0;i<3;i++){const b=button('',()=>{if(!model.window){say('Wait for the green SYNC window.');return;}turn(i);paint();say('Turning a dial also moves its neighbour.');if(values.every((v,i)=>v===target[i]))win();},row);b.className='relay-dial';buttons.push(b);}button('HINT',()=>{onAssist();say('Each dial receives turns from itself and the previous dial. Eight turns return a dial to its starting point.');});update=()=>{model.window=time%1.6<.7;lamp.textContent=model.window?'SYNC · TURN NOW':'WAIT FOR SYNC';lamp.classList.toggle('ready',model.window);};paint();say('Align all three targets');}
 function sweep(){let remaining=12,started=false,end=0,spawnAt=0,serial=0;const targets=new Map();model={type:8,remaining,started:false};instructions.textContent='Clear 12 moving static icons in 20 seconds. Tap or click them; keyboard users can Tab + Enter. Missed icons are replaced.';const field=document.createElement('div');field.className='relay-sweep';area.append(field);function spawn(){const id=serial++,x=relayRandom(78),y=relayRandom(65),b=button('✦',()=>{if(!started)return;b.remove();targets.delete(id);remaining--;model.remaining=remaining;if(remaining===0)win();},field);b.className='relay-static';b.setAttribute('aria-label','Clear static '+(id+1));targets.set(id,{b,x,y,born:time});}button('START / RETRY',()=>{field.replaceChildren();targets.clear();remaining=12;model.remaining=12;started=true;model.started=true;end=time+20;spawnAt=time+.6;for(let i=0;i<3;i++)spawn();});update=()=>{if(!started)return;if(time>=end){started=false;model.started=false;field.replaceChildren();targets.clear();onAssist();say('Time up. Press START / RETRY for a fresh sweep.');return;}if(time>=spawnAt){spawnAt=time+.5;if(targets.size<5)spawn();}for(const [id,q]of targets){if(time-q.born>4){q.b.remove();targets.delete(id);continue;}q.b.style.left=(q.x+Math.floor(Math.sin((time-q.born)*2+id)*4))+'%';q.b.style.top=(q.y+Math.floor(Math.cos((time-q.born)*2)*4))+'%';}say(remaining+' static left · '+Math.ceil(end-time)+'s');};say('Ready · 12 static / 20 seconds');}
 function frame(now){if(!alive||done)return;if(!host.isConnected||host.closest('[hidden]')){session.dispose();return;}const dt=Math.min(.05,(now-last)/1000);last=now;if(!document.hidden){time+=dt;update?.(dt);}raf=requestAnimationFrame(frame);}
 build();raf=requestAnimationFrame(frame);return session;
};
