/* Shared five-world boss state machine: victory requires weakpoint damage. */
function resetWeakpointBoss(c){const b=c.boss;Object.assign(b,{hp:100+c.world.index*20,maxHP:100+c.world.index*20,phase:1,state:'rest',clock:0,cycle:0,pattern:'slam',active:false,done:false,hitDuring:false,evaded:false,perfect:false,hits:0,hitCD:0,stagger:0,fire:99,supply:false,timer:0});c.world.platforms=c.world.platforms.filter(p=>!p.bossPlatform);c.world.platforms.push(...[140,440].map(dx=>({x:c.world.bossStart+dx,baseX:c.world.bossStart+dx,y:282,w:106,bossPlatform:true})));c.enemyShots=[];}
function bossNextAttack(c){const b=c.boss;const patterns=b.phase===1?['slam','volley','lunge']:b.phase===2?['shockwave','lunge','volley','slam']:['burst','shockwave','lunge','volley'];b.pattern=patterns[b.cycle++%patterns.length];b.state='windup';b.clock=0;b.targetX=c.p.x;b.startX=c.p.x;b.startY=c.p.y;b.hitDuring=false;b.evaded=false;b.perfect=false;b.hits=0;const direction=c.p.x<c.world.bossStart+350?1:-1;b.x=clamp(c.p.x+direction*105,c.world.bossStart+50,c.world.bossEnd-50);b.y=250;b.tell=b.phase===3?.62:.98-c.world.index*.04;if(b.pattern==='burst')b.tell=1.1;freeMessage(({slam:'SLAM: leave the marked ground!',volley:'VOLLEY: jump or dash through the shot!',lunge:'LUNGE: dodge the marked lane!',shockwave:'SHOCKWAVE: get onto a raised platform!',burst:'BURST: climb a platform; a last-moment dash earns a big opening!'})[b.pattern],b.tell+.8);}
function updateWeakpointBoss(c,dt){const b=c.boss,p=c.p,w=c.world;if(b.hp===undefined)resetWeakpointBoss(c);if(p.x>w.bossStart&&!b.active&&!b.done){b.active=true;c.checkpoint=w.bossStart+48;c.hearts=4;bossNextAttack(c);}if(!b.active||b.done)return;p.x=clamp(p.x,w.bossStart+12,w.bossEnd-12);b.clock+=dt;b.hitCD=Math.max(0,b.hitCD-dt);b.timer+=dt;
 const phase=b.hp<=b.maxHP*.3?3:b.hp<=b.maxHP*.6?2:1;if(phase!==b.phase){b.phase=phase;c.enemyShots=[];b.state='rest';b.clock=-.6;freeMessage(phase===2?'PHASE 2 · Platforms rise. Beware the marked hazard strip!':'PHASE 3 · Faster attacks, more openings. Watch the burst tell!',3);}
 for(const f of w.platforms.filter(f=>f.bossPlatform)){const old=f.y,target=b.phase>=2?218+Math.sin(c.time*1.1+f.x)*7:282;f.y+=clamp(target-f.y,-60*dt,60*dt);if(p.grounded&&p.floor===f)p.y+=f.y-old;}
 const hazard=w.bossStart+300;const hazardOn=b.phase>=2&&(c.time%4)>1.5;if(hazardOn&&p.x>hazard&&p.x<hazard+70&&p.y>272)freeDamage();
 if(b.state==='rest'){if(b.clock>(b.phase===3?.3:.65))bossNextAttack(c);return;}
 if(b.state==='windup'){if(b.pattern==='burst'&&p.dash>0&&b.tell-b.clock<.10)b.perfect=true;if(b.clock>=b.tell){b.state='active';b.clock=0;if(b.pattern==='volley'){const dir=Math.sign(p.x-b.x)||-1;for(let i=0;i<(b.phase===3?3:2);i++)c.enemyShots.push({x:b.x-dir*i*23,y:i%2?258:247,vx:dir*(150+w.index*14),vy:0,life:.7,bossShot:true});}}return;}
 if(b.state==='active'){if(Math.abs(p.x-b.startX)>28||p.y<b.startY-22||p.dash>0)b.evaded=true;const invulnerable=p.dash>0;let hit=false;if(b.pattern==='slam')hit=Math.abs(p.x-b.targetX)<58&&p.y>254;else if(b.pattern==='lunge'){b.x+=Math.sign(b.targetX-b.x)*Math.min(Math.abs(b.targetX-b.x),330*dt);hit=Math.abs(p.x-b.x)<34&&Math.abs(p.y-25-b.y)<36;}else if(b.pattern==='shockwave'||b.pattern==='burst')hit=p.y>246&&(b.pattern==='shockwave'||b.clock<.20||Math.abs(p.x-b.targetX)<58);if(hit&&!invulnerable)freeDamage();if(b.clock>(b.pattern==='volley'?.9:.45)){c.enemyShots=c.enemyShots.filter(q=>!q.bossShot);b.clock=0;if(!b.hitDuring&&b.evaded){b.state='weak';b.window=b.perfect&&b.pattern==='burst'?2.8:b.phase===3?1.8:2.3;b.hits=0;freeMessage(b.perfect?'PERFECT DODGE · BIG WEAKPOINT OPENING!':'WEAKPOINT OPEN · Move close and ATTACK!',b.window);}else{b.state='rest';freeMessage('Dodge the attack cleanly to expose the weakpoint.',2);}}return;}
 if(b.state==='weak'&&b.clock>=b.window){b.state='rest';b.clock=0;}
}
const weakpointDamage=freeDamage;freeDamage=function(){const c=freeRun;if(!c)return;const before=c.hearts;if(c.boss.active&&!c.boss.done&&c.p.dash>0)return;weakpointDamage();if(c.hearts<before&&c.boss.active){c.boss.hitDuring=true;}};
freeBossHit=function(projectile=null){const c=freeRun;if(!c||c.paused||c.ended)return;const b=c.boss;if(!b.active||b.done)return;if(b.state!=='weak'||b.hitCD>0||b.hits>=2){if(b.state!=='weak')freeMessage('Armoured! Evade its attack, then hit the glowing weakpoint.',2);return;}const source=projectile||{x:c.p.x,y:c.p.y-25};if(Math.abs(source.x-b.x)>(projectile?45:74)||Math.abs(source.y-b.y)>48||(!projectile&&(b.x-c.p.x)*c.p.face<-10))return;b.hp=Math.max(0,b.hp-(b.perfect?22:14));b.hitCD=.32;b.hits++;freeSpark(b.x,b.y,'#fff2aa');if(b.hp===0){b.done=true;b.active=false;c.enemyShots=[];freeMessage('BOSS DEFEATED · Collect the mint key on the right!',6);}};
const weakpointRespawn=freeRespawn;freeRespawn=function(){const c=freeRun,wasBoss=c?.boss.active&&!c.boss.done;weakpointRespawn();if(wasBoss){resetWeakpointBoss(c);c.boss.active=true;c.p.x=c.world.bossStart+48;bossNextAttack(c);freeMessage('Boss attempt lost. HP reset — your three trial keys are kept.',5);}};
const weakpointHUD=updateFreeHUD;updateFreeHUD=function(){weakpointHUD();const c=freeRun;if(!c)return;const b=c.boss;if(b.hp===undefined)return;document.querySelector('#free-boss-title').textContent=c.world.def.boss+' · PHASE '+b.phase;document.querySelector('#free-boss-time').textContent=b.hp+'/'+b.maxHP+' HP · '+(b.state==='weak'?'ATTACK!':b.state==='windup'?'WATCH THE TELL':b.state==='active'?'EVADE':'ARMOURED');document.querySelector('#free-boss-progress').style.width=(b.hp/b.maxHP*100)+'%';};
const weakpointDraw=drawFree;drawFree=function(){weakpointDraw();const c=freeRun,b=c.boss;if(!b.active||b.done)return;const g=freeG;g.save();g.translate(-Math.round(c.camera),0);if(b.phase>=2){const x=c.world.bossStart+300,on=c.time%4>1.5;for(let k=0;k<70;k+=10){retroBox(g,x+k,278,8,4,on?'#ea9e9b':'#cfa982');if(on)retroBox(g,x+k+2,270,4,8,'#f5c481');}retroText(g,on?'HOT':'WARNING',x+35,261);}
 if(b.state==='windup'){const col='#f3b5b6';if(b.pattern==='shockwave'||b.pattern==='burst'){retroBox(g,c.world.bossStart,281,c.world.bossEnd-c.world.bossStart,2,col);retroText(g,'HIGH GROUND',b.x,b.y-65);}else{retroBox(g,b.targetX-58,280,116,3,col);retroText(g,b.pattern.toUpperCase(),b.x,b.y-65);}g.globalAlpha=.55;retroBox(g,b.x-27,b.y-27,54,2,col);retroBox(g,b.x-29,b.y-25,2,48,col);retroBox(g,b.x+27,b.y-25,2,48,col);g.globalAlpha=1;}
 if(b.state==='weak'){const x=Math.round(b.x),y=Math.round(b.y);retroBox(g,x-8,y-9,16,16,'#7dd6bc');retroBox(g,x-5,y-6,10,10,'#fff2a7');retroText(g,b.perfect?'BIG OPENING':'WEAKPOINT',x,y-54);}if(b.state==='active'&&(b.pattern==='shockwave'||b.pattern==='burst'))for(let x=c.world.bossStart;x<c.world.bossEnd;x+=22)retroBox(g,x,271-Math.floor(b.clock*20)%8,14,5,'#ecc493');g.restore();};
