/* Versus-only weapon spacing engine. Adventure movement remains independent. */
const weaponRoster={
 '1':{name:'DUAL DAGGERS',band:'SHORT',range:59,min:0,wind:.12,active:.10,recovery:.18,power:.70,speed:184,dodge:380,dodgeCD:.52,string:'J · J · K',guardDamage:1},
 '2':{name:'CLAW GAUNTLETS',band:'SHORT',range:66,min:0,wind:.15,active:.12,recovery:.19,power:.86,speed:177,dodge:350,dodgeCD:.42,string:'J · J · J · K',guardDamage:1},
 '3':{name:'WOODEN MALLET',band:'SHORT–MID',range:93,min:0,wind:.43,active:.16,recovery:.48,power:1.65,speed:109,dodge:230,dodgeCD:.95,string:'J · K',guardDamage:2},
 '4':{name:'FETCH DISC',band:'MID–LONG',range:220,min:65,wind:.26,active:.12,recovery:.30,power:.83,speed:147,dodge:310,dodgeCD:.70,string:'J OUT · RETURN · K',projectile:'disc',guardDamage:1.5},
 '5':{name:'THROWING KNIVES',band:'LONG',range:265,min:100,wind:.19,active:.10,recovery:.24,power:.67,speed:178,dodge:355,dodgeCD:.62,string:'J · J · K FAN',projectile:'knife',guardDamage:1},
 '6':{name:'WIND STAFF',band:'LONG',range:275,min:95,wind:.52,active:.15,recovery:.38,power:.83,speed:139,dodge:290,dodgeCD:.80,string:'J CHARGE · K GUST',projectile:'wind',guardDamage:1},
 '7':{name:'SPIKED CLUB',band:'SHORT–MID',range:84,min:0,wind:.28,active:.15,recovery:.31,power:1.15,speed:128,dodge:260,dodgeCD:.82,string:'J · J · K',guardDamage:1.5}
};
function initWeaponFighter(f){Object.assign(f,{energy:60,guardHP:3,guardLock:0,guardAge:1,guardReleased:1,wasGuard:false,dodgeTime:0,dodgeCD:0,dodgeAge:0,dodgeDir:0,chain:0,chainUntil:0,bufferedMove:null,discOut:false,weaponFlash:0,stun:0});}
const weaponBegin=beginMatch;beginMatch=async function(id=selectedMap){await weaponBegin(id);if(match){match.weaponShots=[];for(const f of [match.player,match.npc])initWeaponFighter(f);toastBattle('J LIGHT · K HEAVY · SHIFT DODGE (25) · HOLD R GUARD');updateBattleHUD();}};
function weaponPhase(a){return !a?'ready':a.t<a.windup?'windup':a.t<a.windup+a.active?'active':'recovery';}
function weaponDodge(f,dir){if(!match||match.paused||match.ended||match.countdown>0||f.stun>0||f.action||f.dodgeTime>0||f.dodgeCD>0)return false;if(f.energy<25){if(f.side==='player')toastBattle('Dodge needs 25 Energy');return false;}const w=weaponRoster[f.id];f.energy-=25;f.guard=false;f.dodgeTime=.28;f.dodgeAge=0;f.dodgeDir=dir||-f.face;f.dodgeCD=w.dodgeCD;f.bufferedMove=null;particles(f.x,f.y-5,5,'#cee9ff',.5);return true;}
doMove=function(f,type){if(!match||match.paused||match.ended||match.countdown>0||f.stun>0||f.dodgeTime>0)return;const w=weaponRoster[f.id];if(f.action||f.cooldown>0){if(f.side==='player'&&f.cooldown<=.2)f.bufferedMove={type,until:match.elapsed+.24};return;}if(w.projectile==='disc'&&f.discOut){if(f.side==='player')toastBattle('Catch your disc before throwing again');return;}if(type==='skill'&&(f.energy<20||f.skillCD>0))return;if(type==='ultimate'&&f.energy<100)return;
 const heavy=type==='heavy',special=type==='skill'||type==='ultimate';f.chain=match.elapsed<f.chainUntil?(f.chain+1)%(f.id==='2'?4:f.id==='3'?2:3):0;f.chainUntil=match.elapsed+1.5;const finisher=heavy&&f.chain>=1;const wind=w.wind*(heavy?1.35:special?1.2:1),active=w.active,recovery=w.recovery*(heavy?1.4:1);f.action={type,t:0,windup:wind,active,duration:wind+active+recovery,damage:w.power*(type==='ultimate'?2.7:special?1.5:heavy?1.5:1)*(finisher?1.2:1),range:w.range+(heavy&&!w.projectile?10:0),guardDamage:w.guardDamage*(heavy?1.6:1),hit:false,launched:false,chain:f.chain,finisher};f.cooldown=f.action.duration;f.guard=false;f.energy=Math.max(0,f.energy-(type==='ultimate'?100:special?20:0));if(special)f.skillCD=2.5;
};
function weaponImpact(attacker,defender,a,sourceX=attacker.x){if(defender.invulnerable>0||defender.dodgeTime>0&&defender.dodgeAge>=.025&&defender.dodgeAge<.20)return false;const w=weaponRoster[attacker.id];const blocked=defender.guard&&defender.face*(sourceX-defender.x)>0;const parried=blocked&&defender.guardAge<=.13&&defender.guardReleased>=.25;
 if(parried){attacker.stun=.48;attacker.action=null;attacker.cooldown=.48;defender.energy=clamp(defender.energy+8,0,100);defender.guardAge=.2;defender.weaponFlash=.2;particles(defender.x,defender.y-43,10,'#c4f6ff');toastBattle('PARRY · COUNTER NOW');return true;}
 let damage=Math.max(1,Math.round((5+animals[attacker.id].attack*.085)*a.damage*(1-animals[defender.id].def/240)));if(w.min&&Math.abs(attacker.x-defender.x)<w.min)damage=Math.max(1,Math.round(damage*.55));const punish=weaponPhase(defender.action)==='recovery';if(punish)damage=Math.round(damage*1.25);
 if(blocked){defender.guardHP-=a.guardDamage;defender.energy=Math.max(0,defender.energy-(attacker.id==='4'?15:7));damage=Math.max(1,Math.round(damage*.18));defender.weaponFlash=.18;if(defender.id==='7'&&Math.abs(attacker.x-defender.x)<105){attacker.hp=Math.max(0,attacker.hp-2);particles(attacker.x,attacker.y-35,4,'#efc1e5');}if(defender.guardHP<=0||defender.energy<=0){defender.guard=false;defender.guardLock=1.2;defender.stun=.72;defender.guardHP=0;toastBattle('GUARD BREAK · VULNERABLE');}particles(defender.x,defender.y-42,8,'#c9f4ff');}
 else{defender.stun=defender.id==='7'?.09:attacker.id==='3'?.29:.18;defender.action=null;defender.bufferedMove=null;defender.vx=attacker.face*(attacker.id==='6'?235:attacker.id==='3'?145:85);match.shake=motion.matches?0:2.5;particles(defender.x,defender.y-40,12,'#ffe1ad');}
 defender.hp=Math.max(0,defender.hp-damage);defender.invulnerable=.09;defender.energy=clamp(defender.energy+(blocked?0:3),0,100);attacker.energy=clamp(attacker.energy+5,0,100);attacker.combo=match.elapsed-attacker.lastHit<1.5?attacker.combo+1:1;attacker.lastHit=match.elapsed;match.hits++;match.hitStop=motion.matches?0:.035;match.numbers.push({x:defender.x,y:defender.y-91,text:blocked?'BLOCK':punish?'PUNISH −'+damage:'−'+damage,life:.7,color:blocked?'#c4f6ff':'#fff0c5'});if(defender.hp<=0||attacker.hp<=0)endBattle(defender.hp<=0?(defender.side==='npc'?'PLAYER WINS!':'NPC WINS!'):(attacker.side==='npc'?'PLAYER WINS!':'NPC WINS!'));return true;
}
landHit=function(a,d){const hit=a.action;if(!hit||weaponPhase(hit)!=='active'||hit.hit||Math.abs(a.x-d.x)>hit.range||Math.abs(a.y-d.y)>58||(d.x-a.x)*a.face<0)return;if(weaponImpact(a,d,hit))hit.hit=true;};
function launchWeapon(f,a){const w=weaponRoster[f.id];if(!w.projectile)return;f.discOut=w.projectile==='disc';const count=f.id==='5'&&a.type==='heavy'?3:1;for(let i=0;i<count;i++)match.weaponShots.push({owner:f,kind:w.projectile,x:f.x+f.face*24,y:f.y-42,vx:f.face*(w.projectile==='wind'?240:360),vy:(i-(count-1)/2)*65,start:f.x,range:a.range,returning:false,hit:false,life:2.5,a:{...a},face:f.face});}
function updateWeaponShots(dt){for(const q of match.weaponShots){q.life-=dt;const f=q.owner,target=f===match.player?match.npc:match.player;const oldX=q.x;if(q.returning){q.vx=Math.sign(f.x-q.x)*410;q.y+=(f.y-42-q.y)*Math.min(1,dt*9);}q.x+=q.vx*dt;q.y+=q.vy*dt;const crossed=target.x>=Math.min(oldX,q.x)-13&&target.x<=Math.max(oldX,q.x)+13;if(!q.hit&&crossed&&Math.abs(q.y-(target.y-40))<28){if(weaponImpact(f,target,q.a,q.x-Math.sign(q.vx)*18)){q.hit=true;if(q.kind!=='disc')q.life=0;}}if(q.kind==='disc'){if(!q.returning&&Math.abs(q.x-q.start)>=q.range){q.returning=true;q.hit=false;}if(q.returning&&Math.abs(q.x-f.x)<21){q.life=0;f.discOut=false;f.energy=clamp(f.energy+4,0,100);}}else if(Math.abs(q.x-q.start)>q.range)q.life=0;if(q.life<=0&&q.kind==='disc')f.discOut=false;}match.weaponShots=match.weaponShots.filter(q=>q.life>0);}
updateFighter=function(f,other,dt){for(const k of ['cooldown','skillCD','stun','invulnerable','land','dodgeCD','guardLock','weaponFlash'])f[k]=Math.max(0,(f[k]||0)-dt);if(f.guard){f.guardAge=f.wasGuard?f.guardAge+dt:0;f.energy=Math.max(0,f.energy-dt*8);if(!f.energy){f.guard=false;f.guardLock=1;f.stun=.6;}}else{if(f.wasGuard)f.guardReleased=0;f.guardReleased+=dt;f.guardAge=1;if(!f.guardLock)f.guardHP=Math.min(3,f.guardHP+dt*.65);}f.wasGuard=f.guard;if(!f.guard&&!f.dodgeTime)f.energy=Math.min(100,f.energy+dt*(f.action?3:10));if(!f.action&&!f.dodgeTime)f.face=other.x>=f.x?1:-1;
 if(f.dodgeTime>0){f.dodgeTime=Math.max(0,f.dodgeTime-dt);f.dodgeAge+=dt;f.vx=f.dodgeDir*weaponRoster[f.id].dodge*(f.dodgeAge>.2?.55:1);f.guard=false;}
 if(f.action){const a=f.action;a.t+=dt;if(weaponPhase(a)==='active'){if(weaponRoster[f.id].projectile){if(!a.launched){a.launched=true;launchWeapon(f,a);}}else landHit(f,other);}if(f.action&&a.t>=a.duration)f.action=null;}
 if(f.bufferedMove&&f.bufferedMove.until<match.elapsed)f.bufferedMove=null;if(f.bufferedMove&&!f.action&&f.cooldown<=0){const type=f.bufferedMove.type;f.bufferedMove=null;doMove(f,type);}
 f.x=clamp(f.x+f.vx*dt,32,608);f.vy+=match.def.gravity*dt;f.y+=f.vy*dt;if(f.y>=groundY){if(f.vy>150){f.land=.14;particles(f.x,groundY,5,match.def.edge,.5);}f.y=groundY;f.vy=0;}
};
thinkNPC=function(dt){const n=match.npc,p=match.player,w=weaponRoster[n.id],dist=Math.abs(p.x-n.x),toward=Math.sign(p.x-n.x);match.aiThink-=dt;match.aiGuard=Math.max(0,match.aiGuard-dt);n.guard=match.aiGuard>0&&!n.action&&!n.dodgeTime&&!n.stun&&!n.guardLock&&n.energy>0;n.vx=n.stun>0?n.vx*.88:0;if(!n.stun&&!n.action&&!n.guard&&!n.dodgeTime){const desired=w.projectile?w.range*.63:w.range*.72;n.vx=(dist>desired+15?toward:dist<desired-25?-toward:0)*w.speed*.83;}
 if(match.aiThink>0||n.stun||n.dodgeTime)return;match.aiThink=.20+Math.random()*.16;const threat=p.action&&weaponPhase(p.action)==='windup'&&dist<weaponRoster[p.id].range+20;if(threat&&Math.random()<.63){if(n.energy>=25&&Math.random()<.55)weaponDodge(n,-toward);else match.aiGuard=.45;return;}if(!n.action&&dist<w.range-5){if(weaponPhase(p.action)==='recovery'){doMove(n,'heavy');return;}doMove(n,n.energy>=100?'ultimate':Math.random()<.22?'heavy':'attack');}
};
updateMatch=function(dt){if(!match||match.paused||match.ended)return;if(match.hitStop>0){match.hitStop-=dt;return;}match.elapsed+=dt;if(match.countdown>0){match.countdown-=dt;return;}match.time=Math.max(0,match.time-dt);if(!match.time){endBattle('TIME');return;}const p=match.player,n=match.npc,move=joystickX||Number(arenaKeys.has('d')||arenaKeys.has('arrowright'))-Number(arenaKeys.has('a')||arenaKeys.has('arrowleft'));p.guard=(guardTouch||arenaKeys.has('r'))&&!p.action&&!p.dodgeTime&&!p.stun&&!p.guardLock&&p.energy>0&&p.y>=groundY-1;p.vx=p.stun>0?p.vx*.88:!p.guard&&!p.dodgeTime?move*weaponRoster[p.id].speed*(p.action?.32:1):0;
 for(const [key,type]of [['j','attack'],['k','heavy'],['e','skill'],['q','ultimate']])if(arenaKeys.has(key))doMove(p,type);thinkNPC(dt);updateFighter(p,n,dt);if(!match.ended)updateFighter(n,p,dt);if(!match.ended)updateWeaponShots(dt);if(Math.abs(p.x-n.x)<31&&Math.abs(p.y-n.y)<45&&!p.dodgeTime&&!n.dodgeTime){const middle=(p.x+n.x)/2,dir=p.x<n.x?1:-1;p.x=clamp(middle-dir*16,32,608);n.x=clamp(middle+dir*16,32,608);}match.shake=Math.max(0,match.shake-dt*18);for(const q of match.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=110*dt;}match.particles=match.particles.filter(q=>q.life>0);for(const q of match.numbers){q.life-=dt;q.y-=dt*25;}match.numbers=match.numbers.filter(q=>q.life>0);
};
const weaponEnd=endBattle;endBattle=function(title){const m=match,before=m?{...m.stocks}:null;weaponEnd(title);if(m&&!m.ended&&(m.player.hp<=0||m.npc.hp<=0))weaponEnd(title);if(m&&!m.ended){for(const side of ['player','npc'])if(before[side]!==m.stocks[side]){initWeaponFighter(m[side]);m[side].invulnerable=1.8;m.weaponShots=[];m.player.discOut=m.npc.discOut=false;}}};
const dodgeButton=document.createElement('button');dodgeButton.id='dodge-btn';dodgeButton.className='fight-button';dodgeButton.innerHTML='DODGE<small>SHIFT · 25</small>';dodgeButton.style.cssText='right:450px;bottom:35px;pointer-events:auto;background:#637eaa';document.querySelector('.match-controls').append(dodgeButton);
function playerWeaponDodge(){if(scene!=='battle'||!match)return;const direction=joystickX||Number(arenaKeys.has('d')||arenaKeys.has('arrowright'))-Number(arenaKeys.has('a')||arenaKeys.has('arrowleft'));weaponDodge(match.player,Math.sign(direction)||-match.player.face);}
dodgeButton.addEventListener('pointerdown',e=>{e.preventDefault();playerWeaponDodge();});dodgeButton.addEventListener('click',e=>{if(e.detail===0)playerWeaponDodge();});addEventListener('keydown',e=>{if(scene==='battle'&&e.key==='Shift'&&!e.repeat){e.preventDefault();playerWeaponDodge();}});
for(const side of ['player','npc']){const el=document.createElement('div');el.id=side+'-weapon-info';el.style.cssText='font-size:10px;line-height:1.8;margin-top:8px;color:#fff4d8;text-shadow:1px 1px #443e62';document.querySelector('#'+side+'-energy').closest('.energy-row').after(el);}
const weaponHUD=updateBattleHUD;updateBattleHUD=function(){weaponHUD();if(!match)return;for(const side of ['player','npc']){const f=match[side],w=weaponRoster[f.id];document.querySelector('#'+side+'-weapon-info').textContent=w.name+' · '+w.band+' · GUARD '+(f.guardLock?'BROKEN':'◆'.repeat(Math.ceil(f.guardHP??3))+'◇'.repeat(3-Math.ceil(f.guardHP??3)));}dodgeButton.disabled=match.player.energy<25||match.player.dodgeCD>0;};
document.querySelector('.battle-note').textContent='J LIGHT · K HEAVY · SHIFT + DIRECTION DODGE · HOLD R GUARD · TAP R ON IMPACT TO PARRY';
// Weapons render on a native 128px transparent layer before nearest-neighbour display.
const weaponArtCache=new Map();
function weaponArt(id,phase,frame=0){const key=id+phase+frame;if(weaponArtCache.has(key))return weaponArtCache.get(key);const c=document.createElement('canvas');c.width=c.height=128;const g=c.getContext('2d');g.imageSmoothingEnabled=false;if(frame%2===1){g.translate(0,phase==='windup'?-5:phase==='active'?7:0);}const R=(x,y,w,h,col)=>{g.fillStyle=col;g.fillRect(Math.round(x),Math.round(y),w,h);};const metal='#d9edf4',edge='#777493',gold='#e7bb77',wood='#987159';g.translate(phase==='active'?10:phase==='windup'?-8:0,phase==='windup'?-16:phase==='recovery'?8:0);if(phase==='guard'){g.translate(-13,-15);}
 function blade(x,y){R(x,y,3,20,edge);R(x+1,y,2,16,metal);R(x-3,y+18,9,3,gold);R(x,y+21,3,7,wood);}
 if(id==='1'){blade(99,70);blade(34,81);}if(id==='2'){for(let k=0;k<3;k++){R(91+k*4,79-k*2,2,17,edge);R(92+k*4,79-k*2,1,12,metal);}R(88,94,16,7,'#788fba');for(let k=0;k<3;k++)R(30+k*4,88,2,10,metal);}
 if(id==='3'){R(95,61,5,43,wood);R(96,61,1,38,gold);R(80,57,35,22,edge);R(82,58,31,18,'#bd956a');R(84,59,27,4,'#e3bf88');R(86,66,2,9,wood);R(106,64,2,11,wood);}
 if(id==='4'){R(86,83,27,4,edge);R(81,87,36,9,edge);R(86,95,27,4,edge);R(85,86,28,8,'#85bace');R(91,87,15,5,gold);R(97,88,4,3,metal);}
 if(id==='5'){blade(96,72);R(38,95,8,3,gold);R(39,98,5,12,edge);}
 if(id==='6'){R(94,48,4,68,wood);R(95,48,1,66,gold);R(86,45,19,3,gold);R(82,36,5,12,gold);R(103,36,5,12,gold);R(87,29,17,4,gold);R(91,35,10,8,'#a9eddf');R(94,33,4,12,metal);}
 if(id==='7'){R(94,74,5,32,wood);R(87,59,19,26,edge);R(89,61,15,21,'#abb0c7');R(85,62,3,3,metal);R(105,64,4,3,metal);R(92,55,3,5,metal);R(86,75,3,3,metal);R(105,76,4,3,metal);}
 weaponArtCache.set(key,c);return c;}
const weaponBaseFighter=drawFighter;drawFighter=function(g,f,t){if(scene!=='battle'||!f.side){weaponBaseFighter(g,f,t);return;}const a=f.action,phase=weaponPhase(a),w=weaponRoster[f.id];let pose='idle',frame=Math.floor(t*3)%6;if(a){pose=a.type==='heavy'?'heavy':'attack';frame=phase==='windup'?1:phase==='active'?3:5;}else if(f.stun>0){pose='guard';frame=5;}else if(f.dodgeTime>0){pose='jump';frame=2;}else if(f.guard){pose='guard';frame=0;}else if(Math.abs(f.vx)>15){pose='walk';frame=Math.floor(t*12)%6;}
 g.save();g.imageSmoothingEnabled=false;
 // Effective reach is shown during a tell; ranged fighters also show their weak close zone.
 if(a&&phase!=='recovery'){g.globalAlpha=.55;g.fillStyle=phase==='windup'?'#e9b77d':'#c8f0de';const left=f.face>0?f.x:f.x-a.range;g.fillRect(Math.round(left),groundY+4,a.range,2);for(let x=0;x<a.range;x+=14)g.fillRect(Math.round(left+x),groundY+2,2,4);if(w.min){g.fillStyle='#db9aa3';g.fillRect(Math.round(f.face>0?f.x:f.x-w.min),groundY+7,w.min,1);}g.globalAlpha=1;}
 g.translate(Math.round(f.x),Math.round(f.y));g.scale(f.face,1);if(f.dodgeTime>0&&!motion.matches){g.globalAlpha=.2;g.drawImage(retroSprite(f.id,'jump',2),-56-f.dodgeDir*f.face*18,-103,112,112);g.globalAlpha=1;}if(f.stun>0)g.rotate(-.14);else if(f.dodgeTime>0)g.rotate(-.18*f.dodgeDir*f.face);else if(phase==='windup')g.rotate(-.08);else if(phase==='active')g.rotate(.08);g.drawImage(retroSprite(f.id,pose,frame),-56,-106,112,112);if(!(f.id==='4'&&f.discOut))g.drawImage(weaponArt(f.id,f.guard?'guard':phase,a?.chain||0),-56,-106,112,112);
 if(phase==='active'&&!w.projectile){g.globalAlpha=.7;const reach=Math.min(100,a.range);for(let i=0;i<8;i++){const x=24+i*(reach-24)/8,y=-66+i*i*.6;g.fillStyle=i%2?'#fff0c4':'#b9e9f0';g.fillRect(Math.round(x),Math.round(y),5,3);}g.globalAlpha=1;}if(f.weaponFlash>0){g.fillStyle='#d5faff';g.fillRect(20,-51,18,2);g.fillRect(28,-59,2,18);}g.restore();
 const label=f.stun>0?'STAGGER':f.dodgeTime>0?'DODGE':f.guard?'GUARD':phase==='windup'?(a.type==='heavy'?'HEAVY TELL':'WINDUP '+(a.chain+1)):phase==='active'?'STRIKE':phase==='recovery'?'RECOVERY':w.string;retroText(g,label,f.x,f.y-111,phase==='recovery'?'#a6e5f4':'#fff1cb');
};
const weaponBaseDraw=drawMatch;drawMatch=function(){weaponBaseDraw();if(!match)return;const g=arenaCtx;g.save();for(const q of match.weaponShots||[]){const x=Math.round(q.x),y=Math.round(q.y);g.fillStyle=q.kind==='wind'?'#c0f6ed':'#f7deae';if(q.kind==='disc'){g.fillRect(x-9,y-3,18,6);g.fillStyle='#7dabc4';g.fillRect(x-6,y-2,12,3);}else if(q.kind==='knife'){g.fillRect(x-8,y,16,2);g.fillStyle='#8aa5b7';g.fillRect(x-8*q.face,y-2,3,6);}else{for(let i=0;i<4;i++)g.fillRect(x-9+i*4,y-9+Math.abs(1-i)*3,3,14-Math.abs(1-i)*3);}if(!motion.matches){g.globalAlpha=.3;g.fillRect(x-Math.sign(q.vx)*20,y,12,2);g.globalAlpha=1;}}g.restore();};
const weaponDescriptions={1:'Dua dagger · Kombo pantas, dodge jauh.',2:'Claw gauntlets · Slash pantas, dodge cepat pulih.',3:'Mallet kayu · Pukulan berat, pecahkan guard.',4:'Fetch-disc · Baling dan tangkap; kurangkan Energy guard.',5:'Throwing knives · Jaga jarak; lemah bila terlalu dekat.',6:'Wind staff · Charge perlahan, gust menolak lawan.',7:'Spiked club · Sukar stagger; block membalas duri.'};
const weaponSelection=renderFighters;renderFighters=function(){weaponSelection();for(const side of ['player','npc']){const id=resolvedFighter(side);if(id&&(side==='player'||playerConfirmed))document.querySelector('#'+side+'-skill').textContent=weaponDescriptions[id]+' '+weaponRoster[id].band;}};
